import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { getAuthContext, requireOrgId, canDelete } from "@/lib/rbac";
import { logger } from "@/lib/logger";

type Params = { params: Promise<{ id: string }> };

// GET /api/landing-pages/[id]/comments — 파트너 댓글 관리 목록
export async function GET(_req: Request, { params }: Params) {
  try {
    const ctx   = await getAuthContext();
    const orgId = requireOrgId(ctx);
    const { id } = await params;

    const page = await prisma.crmLandingPage.findFirst({
      where: { id, organizationId: orgId },
      select: { id: true },
    });
    if (!page) return NextResponse.json({ ok: false }, { status: 404 });

    const comments = await prisma.crmLandingComment.findMany({
      where:   { landingPageId: id },
      orderBy: { createdAt: "desc" },
      take:    100,
      select:  { id: true, authorName: true, content: true, isAutoGenerated: true, createdAt: true },
    });

    return NextResponse.json({ ok: true, comments });
  } catch (err) {
    logger.error("[GET /api/landing-pages/[id]/comments]", { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}

// DELETE /api/landing-pages/[id]/comments?commentId=xxx
export async function DELETE(req: Request, { params }: Params) {
  try {
    const ctx   = await getAuthContext();
    const orgId = requireOrgId(ctx);
    const { id } = await params;

    if (!canDelete(ctx)) {
      return NextResponse.json({ ok: false, message: "삭제 권한이 없습니다." }, { status: 403 });
    }

    const { searchParams } = new URL(req.url);
    const commentId = searchParams.get("commentId");
    if (!commentId) {
      return NextResponse.json({ ok: false, message: "commentId 필수" }, { status: 400 });
    }

    // 소유권 검증 (랜딩 → 조직)
    const comment = await prisma.crmLandingComment.findFirst({
      where: { id: commentId, landingPage: { organizationId: orgId, id } },
      select: { id: true },
    });
    if (!comment) return NextResponse.json({ ok: false }, { status: 404 });

    await prisma.crmLandingComment.delete({ where: { id: commentId } });

    logger.log("[DELETE /api/landing-pages/[id]/comments]", { commentId, landingPageId: id, orgId });

    return NextResponse.json({ ok: true });
  } catch (err) {
    logger.error("[DELETE /api/landing-pages/[id]/comments]", { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}
