-- Funnel Wizard Schema Extension (2026-06-24)
-- Phase 1: Add Psychology + PASONA fields to Funnel, FunnelSmsMessage, FunnelEmailMessage
-- Zero data loss migration: all new fields have defaults

-- =============================================================================
-- 1. EXTEND: Funnel (Base Model)
-- =============================================================================
-- Add 5 new fields to track creator, visibility, psychology, versioning
ALTER TABLE "Funnel" ADD COLUMN "createdByUserId" TEXT;
ALTER TABLE "Funnel" ADD COLUMN "visibility" VARCHAR(10) NOT NULL DEFAULT 'PUBLIC';
ALTER TABLE "Funnel" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Funnel" ADD COLUMN "psychologyLens" VARCHAR(3);
ALTER TABLE "Funnel" ADD COLUMN "templateVersion" INTEGER NOT NULL DEFAULT 1;

-- Add composite indexes for Funnel (query optimization)
CREATE INDEX "idx_funnel_org_creator_time" ON "Funnel"("organizationId", "createdByUserId", "createdAt" DESC);
CREATE INDEX "idx_funnel_org_psychology_visibility" ON "Funnel"("organizationId", "psychologyLens", "visibility");
CREATE INDEX "idx_funnel_org_template_version" ON "Funnel"("organizationId", "isActive", "templateVersion" DESC);

-- =============================================================================
-- 2. EXTEND: FunnelSmsMessage (Message-level Psychology)
-- =============================================================================
-- Add PASONA + psychology fields for message-specific targeting
ALTER TABLE "FunnelSmsMessage" ADD COLUMN "pasonaStage" VARCHAR(20);
ALTER TABLE "FunnelSmsMessage" ADD COLUMN "psychologyLens" VARCHAR(3);
ALTER TABLE "FunnelSmsMessage" ADD COLUMN "psychology" VARCHAR(50);
ALTER TABLE "FunnelSmsMessage" ADD COLUMN "segmentCode" VARCHAR(30);
ALTER TABLE "FunnelSmsMessage" ADD COLUMN "templateVariant" VARCHAR(50);
ALTER TABLE "FunnelSmsMessage" ADD COLUMN "dynamicVariables" JSONB;

-- Add composite index for PASONA stage filtering
CREATE INDEX "idx_funnel_sms_message_pasona" ON "FunnelSmsMessage"("funnelSmsId", "pasonaStage", "order");

-- =============================================================================
-- 3. EXTEND: FunnelEmailMessage (Message-level Psychology)
-- =============================================================================
-- Add PASONA + psychology fields for email message targeting
ALTER TABLE "FunnelEmailMessage" ADD COLUMN "pasonaStage" VARCHAR(20);
ALTER TABLE "FunnelEmailMessage" ADD COLUMN "psychologyLens" VARCHAR(3);
ALTER TABLE "FunnelEmailMessage" ADD COLUMN "psychology" VARCHAR(50);
ALTER TABLE "FunnelEmailMessage" ADD COLUMN "segmentCode" VARCHAR(30);
ALTER TABLE "FunnelEmailMessage" ADD COLUMN "templateVariant" VARCHAR(50);
ALTER TABLE "FunnelEmailMessage" ADD COLUMN "dynamicVariables" JSONB;
ALTER TABLE "FunnelEmailMessage" ADD COLUMN "preserveHtmlFormat" BOOLEAN NOT NULL DEFAULT true;

-- Add composite index for PASONA stage filtering
CREATE INDEX "idx_funnel_email_message_pasona" ON "FunnelEmailMessage"("funnelEmailId", "pasonaStage", "order");

-- =============================================================================
-- 4. DATA PRESERVATION (Backward Compatibility)
-- =============================================================================
-- All existing Funnel records will have defaults:
-- - visibility = 'PUBLIC' (backward compatible)
-- - createdByUserId = NULL (can be backfilled from audit logs)
-- - autoGenerated = false (manual creation)
-- - psychologyLens = NULL (to be filled by users)
-- - templateVersion = 1 (first version)

-- All existing FunnelSmsMessage records:
-- - pasonaStage = NULL (optional, can be auto-filled later)
-- - psychologyLens = NULL (optional)
-- - psychology = NULL (optional)
-- - Others default to NULL/JSONB empty object

-- All existing FunnelEmailMessage records:
-- - Same as FunnelSmsMessage
-- - preserveHtmlFormat = true (preserve existing HTML formatting)

-- =============================================================================
-- 5. MIGRATION VALIDATION
-- =============================================================================
-- Query to verify migration:
-- SELECT
--   COUNT(*) as total_funnels,
--   COUNT(CASE WHEN visibility IS NOT NULL THEN 1 END) as has_visibility,
--   COUNT(CASE WHEN psychologyLens IS NOT NULL THEN 1 END) as has_psychology,
--   COUNT(CASE WHEN templateVersion > 0 THEN 1 END) as has_version
-- FROM "Funnel";
