-- Phase 2: Funnel Base Schema Enhancement - 마법사용 필드 5개 추가
-- 목적: Funnel 테이블에 크리에이터/가시성/심리학렌즈/자동생성/버전 필드 추가
-- 호환성: 기존 레코드 100% 호환 (기본값 설정)
-- 주의: 이 마이그레이션은 FunnelSms/FunnelEmail 이후에 실행되어야 함 (Phase 1→2)

-- 1. Funnel 테이블에 신규 필드 추가 (5개)
ALTER TABLE "Funnel" ADD COLUMN "createdByUserId" TEXT,
ADD COLUMN "visibility" VARCHAR(10) NOT NULL DEFAULT 'PUBLIC',
ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "psychologyLens" VARCHAR(3),
ADD COLUMN "templateVersion" INTEGER NOT NULL DEFAULT 1;

-- 2. 새로운 복합 인덱스 추가 (organizationId, createdByUserId, createdAt)
CREATE INDEX "idx_funnel_org_creator_time"
  ON "Funnel"("organizationId", "createdByUserId", "createdAt" DESC);

-- 3. 추가 인덱스: visibility로 필터링 (퍼포먼스)
CREATE INDEX "idx_funnel_org_visibility"
  ON "Funnel"("organizationId", "visibility");

-- 4. 추가 인덱스: 심리학 렌즈별 검색
CREATE INDEX "idx_funnel_org_lens"
  ON "Funnel"("organizationId", "psychologyLens");

-- 주석:
-- - createdByUserId: User.id FK 없음 (다른 조직의 사용자도 가능). 임의로 지정 가능.
-- - visibility: PUBLIC(기본, 모두 볼 수 있음), TEAM(팀원만), PERSONAL(본인만)
-- - autoGenerated: true면 자동생성된 마법사 결과. false면 수동생성.
-- - psychologyLens: L0~L10 심리학 렌즈 (NULL=미분류)
-- - templateVersion: 버전 관리. 1부터 시작. 업데이트할 때마다 증가.
-- - 인덱스 3개: 조직별 크리에이터/시간, 가시성 필터, 렌즈별 분류
