"use client";

import { Sparkles, Trash2 } from "lucide-react";

type MgrComment = {
  id: string;
  authorName: string;
  content: string;
  isAutoGenerated: boolean;
  createdAt: string;
};

interface Props {
  comments: MgrComment[];
  commentEnabled: boolean;
  genCount: number;
  generating: boolean;
  commentMsg: string;
  onToggleEnabled: () => void;
  onGenCountChange: (n: number) => void;
  onGenerate: () => void;
  onDelete: (commentId: string) => void;
}

export function CommentsTab({
  comments, commentEnabled, genCount, generating, commentMsg,
  onToggleEnabled, onGenCountChange, onGenerate, onDelete,
}: Props) {
  return (
    <div className="flex-1 overflow-y-auto p-4 space-y-4">
      {/* 게시판 설정 */}
      <div className="bg-white border border-gray-200 rounded-xl p-4">
        <div className="flex items-center justify-between mb-1">
          <p className="text-sm font-semibold text-gray-700">커뮤니티 Q&amp;A 게시판</p>
          <button
            onClick={onToggleEnabled}
            className={`px-3 py-1 rounded-full text-xs font-medium transition-colors ${
              commentEnabled ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-500"
            }`}
          >
            {commentEnabled ? "활성" : "비활성"}
          </button>
        </div>
        <p className="text-xs text-gray-400">활성화 시 공개 랜딩페이지 하단에 질문·답변 게시판이 노출됩니다.</p>
      </div>

      {/* AI FAQ 시드 생성 */}
      <div className="bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-xl p-4">
        <p className="text-sm font-semibold text-gray-700 flex items-center gap-1.5 mb-2">
          <Sparkles className="w-4 h-4 text-purple-500" /> AI 자주 묻는 질문(FAQ) 등록
        </p>
        <p className="text-xs text-gray-500 mb-3">랜딩 내용을 분석해 자주 묻는 질문 + 운영자 답변을 <b>운영자 명의</b>로 등록합니다. 가짜 후기가 아니라 정직한 Q&amp;A예요.</p>
        <div className="flex items-center gap-2">
          <select
            value={genCount}
            onChange={(e) => onGenCountChange(Number(e.target.value))}
            className="border border-gray-200 rounded-lg px-2 py-1.5 text-sm bg-white"
          >
            {[3, 5, 7, 10].map((n) => <option key={n} value={n}>{n}개</option>)}
          </select>
          <button
            onClick={onGenerate}
            disabled={generating}
            className="flex-1 bg-purple-600 text-white py-1.5 rounded-lg text-sm font-medium hover:bg-purple-700 disabled:opacity-50 flex items-center justify-center gap-1.5"
          >
            {generating ? "생성 중..." : <><Sparkles className="w-3.5 h-3.5" /> FAQ 생성</>}
          </button>
        </div>
        {commentMsg && (
          <p className={`text-xs mt-2 ${commentMsg.includes("완료") ? "text-green-600" : "text-red-500"}`}>
            {commentMsg}
          </p>
        )}
      </div>

      {/* 댓글 목록 */}
      <div className="space-y-2">
        {comments.length === 0 ? (
          <p className="text-center text-sm text-gray-400 py-8">등록된 질문·답변이 없습니다.</p>
        ) : (
          comments.map((c) => (
            <div key={c.id} className="bg-white border border-gray-200 rounded-xl p-4 flex items-start gap-3">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-sm font-semibold">{c.authorName}</span>
                  {c.isAutoGenerated && (
                    <span className="text-[10px] bg-purple-100 text-purple-500 px-1.5 py-0.5 rounded-full">AI생성</span>
                  )}
                  <span className="text-xs text-gray-400 ml-auto">
                    {new Date(c.createdAt).toLocaleDateString("ko-KR")}
                  </span>
                </div>
                <p className="text-sm text-gray-700">{c.content}</p>
              </div>
              <button
                onClick={() => onDelete(c.id)}
                className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors shrink-0"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
