"use client";

import { Sparkles, Trash2, MessageCircleQuestion } from "lucide-react";

type MgrComment = {
  id: string;
  authorName: string;
  content: string;
  isAutoGenerated: boolean;
  createdAt: string;
};

interface Props {
  comments: MgrComment[];
  commentEnabled: boolean;
  genCount: number;
  genDateFrom: string;
  genDateTo: string;
  generating: boolean;
  commentMsg: string;
  onToggleEnabled: () => void;
  onGenCountChange: (n: number) => void;
  onGenDateFromChange: (d: string) => void;
  onGenDateToChange: (d: string) => void;
  onGenerate: () => void;
  onDelete: (commentId: string) => void;
  // 샘플 문의 자동 생성(큐레이션 Q&A, 외부 의존 0) — 관리자/지사만
  canSeed: boolean;
  seeding: boolean;
  onSeed: () => void;
}

export function CommentsTab({
  comments, commentEnabled, genCount, genDateFrom, genDateTo, generating, commentMsg,
  onToggleEnabled, onGenCountChange, onGenDateFromChange, onGenDateToChange, onGenerate, onDelete,
  canSeed, seeding, onSeed,
}: Props) {
  return (
    <div className="flex-1 overflow-y-auto p-4 space-y-4">
      {/* 게시판 설정 */}
      <div className="bg-white border border-gray-200 rounded-xl p-4">
        <div className="flex items-center justify-between mb-1">
          <p className="text-sm font-semibold text-gray-700">커뮤니티 Q&amp;A 게시판</p>
          <button
            onClick={onToggleEnabled}
            className={`px-3 py-1 rounded-full text-xs font-medium transition-colors ${
              commentEnabled ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-500"
            }`}
          >
            {commentEnabled ? "활성" : "비활성"}
          </button>
        </div>
        <p className="text-xs text-gray-400">활성화 시 공개 랜딩페이지 하단에 질문·답변 게시판이 노출됩니다.</p>
      </div>

      {/* 샘플 문의 자동 생성 (큐레이션 Q&A, 외부 연결 없이 안전) — 관리자/지사만 */}
      {canSeed && (
        <div className="bg-green-50 border border-green-200 rounded-xl p-4">
          <p className="text-base font-semibold text-gray-800 flex items-center gap-1.5 mb-1">
            <MessageCircleQuestion className="w-5 h-5 text-green-600" /> 샘플 문의 자동 생성
          </p>
          <p className="text-sm text-gray-600 mb-3" style={{ lineHeight: 1.6 }}>
            크루즈 여행에서 자주 나오는 질문과 친절한 안내 답변을 한 번에 만들어 줍니다. 위에서 고른
            <b> 작성 기간</b>과 <b>개수</b>가 함께 적용되며, 같은 페이지에는 최대 10개까지만 쌓입니다.
            (만들어진 문의는 아래에서 검토·삭제할 수 있어요.)
          </p>
          <button
            onClick={onSeed}
            disabled={seeding}
            style={{ minHeight: 48 }}
            className="w-full bg-green-600 text-white rounded-lg text-base font-semibold hover:bg-green-700 disabled:opacity-50 flex items-center justify-center gap-2 px-4"
          >
            {seeding ? "생성 중..." : <><MessageCircleQuestion className="w-5 h-5" /> 샘플 문의 자동 생성 (최대 10개)</>}
          </button>
        </div>
      )}

      {/* AI FAQ 시드 생성 */}
      <div className="bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-xl p-4">
        <p className="text-sm font-semibold text-gray-700 flex items-center gap-1.5 mb-2">
          <Sparkles className="w-4 h-4 text-purple-500" /> AI 커뮤니티 댓글 생성
        </p>
        <p className="text-xs text-gray-500 mb-3">랜딩 내용을 분석해 질문·고민·경험·응원이 섞인 커뮤니티 댓글(+답글)을 유튜브 댓글처럼 다양하게 생성합니다. 아래 <b>기간</b>에 작성된 것처럼 날짜가 자연스럽게 분산됩니다. 생성 후 <b>검토·삭제</b>할 수 있어요.</p>
        {/* 작성 기간 — 이 기간 안에 날짜가 랜덤 분산되어 오래전부터 쌓인 것처럼 보임 */}
        <div className="flex items-center gap-2 mb-2">
          <span className="text-xs text-gray-500 shrink-0">작성 기간</span>
          <input
            type="date"
            value={genDateFrom}
            onChange={(e) => onGenDateFromChange(e.target.value)}
            className="flex-1 border border-gray-200 rounded-lg px-2 py-1.5 text-sm bg-white"
          />
          <span className="text-xs text-gray-400">~</span>
          <input
            type="date"
            value={genDateTo}
            onChange={(e) => onGenDateToChange(e.target.value)}
            className="flex-1 border border-gray-200 rounded-lg px-2 py-1.5 text-sm bg-white"
          />
        </div>
        <div className="flex items-center gap-2">
          <select
            value={genCount}
            onChange={(e) => onGenCountChange(Number(e.target.value))}
            className="border border-gray-200 rounded-lg px-2 py-1.5 text-sm bg-white"
          >
            {[3, 5, 7, 10].map((n) => <option key={n} value={n}>{n}개</option>)}
          </select>
          <button
            onClick={onGenerate}
            disabled={generating}
            className="flex-1 bg-purple-600 text-white py-1.5 rounded-lg text-sm font-medium hover:bg-purple-700 disabled:opacity-50 flex items-center justify-center gap-1.5"
          >
            {generating ? "생성 중..." : <><Sparkles className="w-3.5 h-3.5" /> 댓글 생성</>}
          </button>
        </div>
        {commentMsg && (
          <p className={`text-xs mt-2 ${commentMsg.includes("완료") ? "text-green-600" : "text-red-500"}`}>
            {commentMsg}
          </p>
        )}
      </div>

      {/* 댓글 목록 */}
      <div className="space-y-2">
        {comments.length === 0 ? (
          <p className="text-center text-sm text-gray-400 py-8">등록된 댓글이 없습니다.</p>
        ) : (
          comments.map((c) => (
            <div key={c.id} className="bg-white border border-gray-200 rounded-xl p-4 flex items-start gap-3">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-sm font-semibold">{c.authorName}</span>
                  {c.isAutoGenerated && (
                    <span className="text-[10px] bg-purple-100 text-purple-500 px-1.5 py-0.5 rounded-full">AI생성</span>
                  )}
                  <span className="text-xs text-gray-400 ml-auto">
                    {new Date(c.createdAt).toLocaleDateString("ko-KR")}
                  </span>
                </div>
                <p className="text-sm text-gray-700">{c.content}</p>
              </div>
              <button
                onClick={() => onDelete(c.id)}
                className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors shrink-0"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
