ALTER TABLE "SalesPlaybook" ADD COLUMN IF NOT EXISTS "scriptTab" TEXT NOT NULL DEFAULT 'GENERAL';
ALTER TABLE "SalesPlaybook" ADD COLUMN IF NOT EXISTS "productCode" TEXT NOT NULL DEFAULT 'ALL';
ALTER TABLE "SalesPlaybook" ADD COLUMN IF NOT EXISTS "sectionOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ScriptPattern" ADD COLUMN IF NOT EXISTS "productCode" TEXT NOT NULL DEFAULT 'ALL';
ALTER TABLE "AiCallLog" ADD COLUMN IF NOT EXISTS "productCode" TEXT NOT NULL DEFAULT 'ALL';
