-- Add funnel wizard fields to Funnel table
ALTER TABLE "Funnel" ADD COLUMN "createdByUserId" TEXT;
ALTER TABLE "Funnel" ADD COLUMN "visibility" TEXT NOT NULL DEFAULT 'PUBLIC';
ALTER TABLE "Funnel" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Funnel" ADD COLUMN "psychologyLens" TEXT;
ALTER TABLE "Funnel" ADD COLUMN "templateVersion" INTEGER NOT NULL DEFAULT 1;

-- Add indexes for wizard performance
CREATE INDEX "Funnel_organizationId_createdByUserId_idx" ON "Funnel"("organizationId", "createdByUserId");
CREATE INDEX "Funnel_organizationId_createdAt_idx" ON "Funnel"("organizationId", "createdAt");
