-- CrmLandingPage: commentEnabled 컬럼 추가
ALTER TABLE "CrmLandingPage" ADD COLUMN IF NOT EXISTS "commentEnabled" BOOLEAN NOT NULL DEFAULT false;

-- CrmLandingComment: 방문자 댓글 테이블 신규
CREATE TABLE "CrmLandingComment" (
  "id"              TEXT        NOT NULL,
  "landingPageId"   TEXT        NOT NULL,
  "authorName"      TEXT        NOT NULL,
  "content"         TEXT        NOT NULL,
  "passwordHash"    TEXT,
  "isAutoGenerated" BOOLEAN     NOT NULL DEFAULT false,
  "createdAt"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "CrmLandingComment_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "CrmLandingComment_landingPageId_fkey"
    FOREIGN KEY ("landingPageId") REFERENCES "CrmLandingPage"("id") ON DELETE CASCADE
);
CREATE INDEX "CrmLandingComment_landingPageId_idx" ON "CrmLandingComment"("landingPageId");
