"use client";

import { useState, useEffect } from "react";
import { useRouter, useParams, useSearchParams } from "next/navigation";
import { ArrowLeft, Eye, Users, MessageSquare } from "lucide-react";
import dynamic from "next/dynamic";
import { RegistrationsTab } from "./components/RegistrationsTab";
import { CommentsTab } from "./components/CommentsTab";

type Registration = {
  id: string;
  name: string;
  phone: string;
  email: string | null;
  utmSource: string | null;
  funnelStarted: boolean;
  createdAt: string;
};

const HtmlEditor = dynamic(
  () => import("@/components/editor/HtmlEditor").then((m) => m.HtmlEditor),
  { ssr: false, loading: () => <div className="h-96 bg-gray-100 animate-pulse rounded-xl" /> }
);

export default function EditLandingPage() {
  const router = useRouter();
  const params = useParams();
  const searchParams = useSearchParams();
  const id = params.id as string;

  const [tab, setTab]           = useState<"editor" | "registrations" | "comments">(
    searchParams.get("tab") === "registrations" ? "registrations" :
    searchParams.get("tab") === "comments" ? "comments" : "editor"
  );
  const [title, setTitle]       = useState("");
  const [slug, setSlug]         = useState("");
  const [html, setHtml]         = useState("");
  const [preview, setPreview]   = useState(false);
  const [saving, setSaving]     = useState(false);
  const [loading, setLoading]   = useState(true);
  const [error, setError]       = useState("");
  const [saveMsg, setSaveMsg]   = useState("");
  const [groups, setGroups]     = useState<{ id: string; name: string; funnelId: string | null }[]>([]);
  const [selectedGroupId, setSelectedGroupId] = useState<string>("");

  // 결제 설정
  const [paymentEnabled, setPaymentEnabled] = useState(false);
  const [paymentType, setPaymentType]       = useState<"onetime" | "subscription">("onetime");
  const [productName, setProductName]       = useState("");
  const [productPrice, setProductPrice]     = useState("");
  const [cycleDay, setCycleDay]             = useState("1");
  const [expireDate, setExpireDate]         = useState("");

  // 등록자 목록
  const [registrations, setRegistrations]     = useState<Registration[]>([]);
  const [regTotal,       setRegTotal]          = useState(0);
  const [regPage,        setRegPage]           = useState(1);
  const [regLoading,     setRegLoading]        = useState(false);

  // 댓글 관리
  type MgrComment = { id: string; authorName: string; content: string; isAutoGenerated: boolean; createdAt: string };
  const [comments,      setComments]     = useState<MgrComment[]>([]);
  const [commentEnabled, setCommentEnabled] = useState(false);
  const [genCount,      setGenCount]     = useState(5);
  const [generating,    setGenerating]   = useState(false);
  const [commentMsg,    setCommentMsg]   = useState("");

  useEffect(() => {
    Promise.all([
      fetch(`/api/landing-pages/${id}`).then((r) => r.json()),
      fetch("/api/groups").then((r) => r.json()),
    ]).then(([pageData, groupData]) => {
      if (pageData.ok && pageData.page) {
        setTitle(pageData.page.title ?? "");
        setSlug(pageData.page.slug ?? "");
        setHtml(pageData.page.htmlContent ?? "");
        setSelectedGroupId(pageData.page.groupId ?? "");
        setCommentEnabled(pageData.page.commentEnabled ?? false);
        setPaymentEnabled(pageData.page.paymentEnabled ?? false);
        setPaymentType(pageData.page.paymentType ?? "onetime");
        setProductName(pageData.page.productName ?? "");
        setProductPrice(String(pageData.page.productPrice ?? ""));
        setCycleDay(String(pageData.page.cycleDay ?? "1"));
        setExpireDate(pageData.page.expireDate ? pageData.page.expireDate.split("T")[0] : "");
      }
      if (groupData.ok) setGroups(groupData.groups ?? []);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, [id]);

  const loadRegistrations = async (p: number) => {
    setRegLoading(true);
    try {
      const res = await fetch(`/api/landing-pages/${id}/registrations?page=${p}&limit=20`);
      const data = await res.json();
      if (data.ok) {
        setRegistrations(data.registrations);
        setRegTotal(data.total);
        setRegPage(p);
      }
    } catch {
      setError("등록자 목록을 불러오지 못했습니다.");
    } finally {
      setRegLoading(false);
    }
  };

  useEffect(() => {
    if (tab === "registrations") loadRegistrations(1);
    if (tab === "comments") loadComments();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab, id]);

  const loadComments = async () => {
    try {
      const res = await fetch(`/api/landing-pages/${id}/comments`);
      const data = await res.json();
      if (data.ok) setComments(data.comments);
    } catch {
      setCommentMsg("후기 목록을 불러오지 못했습니다.");
    }
  };

  const deleteComment = async (commentId: string) => {
    const res = await fetch(`/api/landing-pages/${id}/comments?commentId=${commentId}`, { method: "DELETE" });
    const data = await res.json();
    if (data.ok) setComments((prev) => prev.filter((c) => c.id !== commentId));
  };

  const toggleCommentEnabled = async () => {
    const next = !commentEnabled;
    const res = await fetch(`/api/landing-pages/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ commentEnabled: next }),
    });
    const data = await res.json();
    if (data.ok) setCommentEnabled(next);
  };

  const generateComments = async () => {
    setGenerating(true);
    setCommentMsg("");
    const res = await fetch(`/api/landing-pages/${id}/comments/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ count: genCount }),
    });
    const data = await res.json();
    if (data.ok) {
      setComments((prev) => [...data.comments, ...prev]);
      setCommentMsg(`✅ ${data.comments.length}개 AI 후기 생성 완료`);
    } else {
      setCommentMsg("생성 실패. 다시 시도하세요.");
    }
    setGenerating(false);
  };

  const save = async () => {
    if (!title.trim() || !slug.trim()) {
      setError("제목과 슬러그를 입력하세요.");
      return;
    }
    setSaving(true);
    const res = await fetch(`/api/landing-pages/${id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        title, slug, htmlContent: html,
        groupId: selectedGroupId || null,
        paymentEnabled,
        ...(paymentEnabled ? {
          paymentType,
          productName: productName || null,
          productPrice: parseInt(productPrice) || null,
          ...(paymentType === "subscription" ? { cycleDay: parseInt(cycleDay), expireDate: expireDate || null } : {}),
        } : {}),
      }),
    });
    const data = await res.json();
    setSaving(false);
    if (data.ok) {
      setSaveMsg("저장됐어요!");
      setTimeout(() => setSaveMsg(""), 2000);
    } else {
      setError(data.message ?? "저장 실패");
    }
  };

  if (loading) return <div className="h-screen bg-gray-50 animate-pulse" />;

  return (
    <div className="flex flex-col h-screen bg-gray-50">
      {/* 헤더 */}
      <div className="flex items-center gap-3 px-4 py-3 bg-white border-b border-gray-200 shrink-0">
        <button onClick={() => router.back()} className="text-gray-400 hover:text-gray-700">
          <ArrowLeft className="w-5 h-5" />
        </button>
        <input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="랜딩페이지 제목"
          className="flex-1 text-base font-semibold bg-transparent outline-none"
        />
        {/* 탭 전환 */}
        <div className="flex border border-gray-200 rounded-lg overflow-hidden text-xs">
          <button
            onClick={() => setTab("editor")}
            className={`px-3 py-1.5 font-medium transition-colors ${tab === "editor" ? "bg-navy-900 text-white" : "text-gray-500 hover:bg-gray-50"}`}
          >편집</button>
          <button
            onClick={() => setTab("registrations")}
            className={`px-3 py-1.5 font-medium flex items-center gap-1 transition-colors ${tab === "registrations" ? "bg-navy-900 text-white" : "text-gray-500 hover:bg-gray-50"}`}
          >
            <Users className="w-3 h-3" /> 등록자 {regTotal > 0 && `(${regTotal})`}
          </button>
          <button
            onClick={() => setTab("comments")}
            className={`px-3 py-1.5 font-medium flex items-center gap-1 transition-colors ${tab === "comments" ? "bg-navy-900 text-white" : "text-gray-500 hover:bg-gray-50"}`}
          >
            <MessageSquare className="w-3 h-3" /> 후기 {comments.length > 0 && `(${comments.length})`}
          </button>
        </div>
        {tab === "editor" && (
          <>
            <button onClick={() => setPreview(!preview)} className="text-gray-500 hover:text-navy-900 p-1.5">
              <Eye className="w-4 h-4" />
            </button>
            {error && <span className="text-xs text-red-500">{error}</span>}
            {saveMsg && <span className="text-xs text-green-600">{saveMsg}</span>}
            <button
              onClick={save}
              disabled={saving}
              className="bg-navy-900 text-white px-4 py-1.5 rounded-lg text-sm font-medium disabled:opacity-50"
            >
              {saving ? "저장 중..." : "저장"}
            </button>
          </>
        )}
      </div>

      {/* 에디터 탭 */}
      {tab === "editor" && (
        <>
          {/* 설정 바 */}
          <div className="flex items-center gap-4 px-4 py-2 bg-gray-50 border-b border-gray-100 shrink-0">
            <div className="flex items-center gap-2">
              <label className="text-xs text-gray-500 whitespace-nowrap">슬러그</label>
              <input
                value={slug}
                onChange={(e) => setSlug(e.target.value)}
                placeholder="url-slug"
                className="border border-gray-200 rounded px-2 py-1 text-xs w-40 focus:outline-none focus:border-gold-500"
              />
            </div>
            <div className="flex items-center gap-2 flex-1">
              <label className="text-xs text-gray-500 whitespace-nowrap">등록 고객 배정 그룹</label>
              <select
                value={selectedGroupId}
                onChange={(e) => setSelectedGroupId(e.target.value)}
                className="border border-gray-200 rounded px-2 py-1 text-xs flex-1 max-w-xs focus:outline-none focus:border-gold-500"
              >
                <option value="">그룹 미지정</option>
                {groups.map((g) => (
                  <option key={g.id} value={g.id}>
                    {g.name} {g.funnelId ? "🔄" : ""}
                  </option>
                ))}
              </select>
              <span className="text-xs text-gray-400">🔄 = 등록 즉시 자동 문자</span>
            </div>
            {/* 결제 설정 */}
            <div className="flex items-center gap-3 mt-2 pt-2 border-t border-gray-100">
              <label className="text-xs font-medium text-gray-700 flex items-center gap-1.5">
                <input type="checkbox" checked={paymentEnabled} onChange={(e) => setPaymentEnabled(e.target.checked)} className="w-3.5 h-3.5" />
                결제 기능
              </label>
              {paymentEnabled && (
                <>
                  <select value={paymentType} onChange={(e) => setPaymentType(e.target.value as "onetime" | "subscription")} className="border border-gray-200 rounded px-2 py-1 text-xs">
                    <option value="onetime">일반 결제</option>
                    <option value="subscription">정기 결제</option>
                  </select>
                  <input type="text" value={productName} onChange={(e) => setProductName(e.target.value)} placeholder="상품명" className="border border-gray-200 rounded px-2 py-1 text-xs w-28" />
                  <input type="number" value={productPrice} onChange={(e) => setProductPrice(e.target.value)} placeholder="금액" className="border border-gray-200 rounded px-2 py-1 text-xs w-20" />
                  <span className="text-xs text-gray-400">원</span>
                  {paymentType === "subscription" && (
                    <>
                      <select value={cycleDay} onChange={(e) => setCycleDay(e.target.value)} className="border border-gray-200 rounded px-2 py-1 text-xs">
                        {Array.from({ length: 31 }, (_, i) => <option key={i + 1} value={i + 1}>{i + 1}일</option>)}
                        <option value="90">말일</option>
                      </select>
                      <input type="date" value={expireDate} onChange={(e) => setExpireDate(e.target.value)} className="border border-gray-200 rounded px-2 py-1 text-xs" />
                    </>
                  )}
                </>
              )}
            </div>
          </div>
          <div className="flex-1 overflow-hidden">
            {preview ? (
              <iframe srcDoc={html} className="w-full h-full border-0" title="preview" sandbox="allow-scripts" />
            ) : (
              <HtmlEditor value={html} onChange={setHtml} />
            )}
          </div>
        </>
      )}

      {/* 등록자 목록 탭 */}
      {tab === "registrations" && (
        <RegistrationsTab
          registrations={registrations}
          regTotal={regTotal}
          regPage={regPage}
          regLoading={regLoading}
          onPageChange={loadRegistrations}
        />
      )}

      {/* 댓글 관리 탭 */}
      {tab === "comments" && (
        <CommentsTab
          comments={comments}
          commentEnabled={commentEnabled}
          genCount={genCount}
          generating={generating}
          commentMsg={commentMsg}
          onToggleEnabled={toggleCommentEnabled}
          onGenCountChange={setGenCount}
          onGenerate={generateComments}
          onDelete={deleteComment}
        />
      )}
    </div>
  );
}
