export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getAuthContext, resolveOrgId } from '@/lib/rbac';
import { logger } from '@/lib/logger';
import { getCache, setCache } from '@/lib/redis';

type Params = { params: Promise<{ id: string }> };

/**
 * B2B 랜딩페이지 댓글 타입
 */
interface B2BComment {
  id: string;
  authorName: string;
  content: string;
  isAutoGenerated: boolean;
  createdAt: string;
}

/**
 * GET /api/b2b-landing/[id]/comments?skip=0&limit=10
 * B2B 랜딩페이지 AI 생성 후기 목록 조회
 *
 * Query params:
 * - skip: 페이지 오프셋 (기본 0)
 * - limit: 페이지 크기 (기본 10, 최대 50)
 *
 * Response: { ok: true, comments: [...], total: number, totalPages: number }
 */
export async function GET(req: Request, { params }: Params) {
  try {
    const ctx = await getAuthContext();
    const orgId = resolveOrgId(ctx);
    const { id } = await params;

    // B2B 랜딩페이지 소유권 확인
    const page = await prisma.b2BLandingPage.findFirst({
      where: { id, organizationId: orgId },
      select: { id: true },
    });
    if (!page) {
      return NextResponse.json({ ok: false, error: 'NOT_FOUND', message: '랜딩페이지를 찾을 수 없습니다.' }, { status: 404 });
    }

    // [ENV] 쿼리 파라미터 파싱 및 경계값 검증
    // Issue 27: 경계값 검증 — skip은 최대 PAGINATION_SKIP_MAX, limit은 1~PAGINATION_LIMIT_MAX 범위로 제한
    // Test cases:
    //   - skip=999999999 → clamped to PAGINATION_SKIP_MAX
    //   - limit=0 → fallback to 10
    //   - limit=-5 → clamped to 1
    //   - limit=999 → clamped to PAGINATION_LIMIT_MAX
    const paginationSkipMax = parseInt(process.env.PAGINATION_SKIP_MAX || '10000');
    const paginationLimitMax = parseInt(process.env.PAGINATION_LIMIT_MAX || '50');

    const { searchParams } = new URL(req.url);
    const skipRaw = parseInt(searchParams.get('skip') ?? '0') || 0;
    const skip = Math.min(paginationSkipMax, Math.max(0, skipRaw)); // Clamp: 0 ~ paginationSkipMax

    const rawLimit = parseInt(searchParams.get('limit') ?? '10') || 10;
    const limit = Math.min(paginationLimitMax, Math.max(1, rawLimit)); // Clamp: 1 ~ paginationLimitMax

    // [캐싱] Redis에서 5분 TTL로 캐시된 댓글 목록 조회
    const cacheKey = `b2b:comments:${id}:${skip}:${limit}`;
    const cachedComments = await getCache<{ ok: boolean; comments: B2BComment[]; total: number; totalPages: number }>(cacheKey);
    if (cachedComments) {
      logger.log('[B2B comments] 캐시에서 조회', { id, orgId, skip, limit });
      return NextResponse.json(cachedComments);
    }

    // 전체 댓글 수
    const total = await prisma.b2BLandingComment.count({
      where: { landingPageId: id },
    });

    // 댓글 조회
    const rawComments = await prisma.b2BLandingComment.findMany({
      where: { landingPageId: id },
      orderBy: { createdAt: 'desc' },
      skip,
      take: limit,
      select: {
        id: true,
        authorName: true,
        content: true,
        isAutoGenerated: true,
        createdAt: true,
      },
    });

    // Date를 ISO string으로 변환
    const comments = rawComments.map(c => ({
      ...c,
      createdAt: c.createdAt.toISOString(),
    }));

    const totalPages = Math.ceil(total / limit);

    logger.log('[GET /api/b2b-landing/[id]/comments]', {
      landingPageId: id,
      orgId,
      skip,
      limit,
      total,
      returned: comments.length,
    });

    const response = {
      ok: true,
      comments,
      total,
      totalPages,
    };

    // [캐싱] 응답을 5분 TTL로 Redis에 캐시
    await setCache(cacheKey, response, 300);

    return NextResponse.json(response);
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    const errorCode = err instanceof Error && 'code' in err && typeof (err as object & { code?: unknown }).code === 'string'
        ? String((err as object & { code?: unknown }).code)
        : 'UNKNOWN';
    logger.error('[GET /api/b2b-landing/[id]/comments] Error', {
      error: errorMsg,
      errorCode,
      stack: err instanceof Error ? err.stack?.split('\n').slice(0, 3).join('\n') : undefined,
    });
    return NextResponse.json({ ok: false, error: 'INTERNAL_ERROR', message: '댓글을 불러오지 못했습니다.' }, { status: 500 });
  }
}

/**
 * DELETE /api/b2b-landing/[id]/comments?commentId=xxx
 * B2B 랜딩페이지 댓글 삭제
 */
export async function DELETE(req: Request, { params }: Params) {
  try {
    const ctx = await getAuthContext();
    const orgId = resolveOrgId(ctx);
    const { id } = await params;
    const { searchParams } = new URL(req.url);
    const commentId = searchParams.get('commentId');

    if (!commentId) {
      return NextResponse.json({ ok: false, error: 'INVALID_INPUT', message: 'commentId 필수' }, { status: 400 });
    }

    // 소유권 확인
    const page = await prisma.b2BLandingPage.findFirst({
      where: { id, organizationId: orgId },
      select: { id: true },
    });
    if (!page) {
      return NextResponse.json({ ok: false, error: 'NOT_FOUND', message: '랜딩페이지를 찾을 수 없습니다.' }, { status: 404 });
    }

    await prisma.b2BLandingComment.delete({ where: { id: commentId } });

    logger.log('[DELETE /api/b2b-landing/[id]/comments]', { landingPageId: id, commentId, orgId });
    return NextResponse.json({ ok: true });
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    logger.error('[DELETE /api/b2b-landing/[id]/comments] Error', { error: errorMsg });
    return NextResponse.json({ ok: false, error: 'INTERNAL_ERROR', message: '댓글 삭제 중 오류가 발생했습니다.' }, { status: 500 });
  }
}
