export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getAuthContext, requireOrgId } from '@/lib/rbac';
import { logger } from '@/lib/logger';

type Params = { params: Promise<{ id: string }> };

/**
 * GET /api/b2b-landing/[id]/comments?skip=0&limit=10
 * B2B 랜딩페이지 AI 생성 후기 목록 조회
 *
 * Query params:
 * - skip: 페이지 오프셋 (기본 0)
 * - limit: 페이지 크기 (기본 10, 최대 50)
 *
 * Response: { ok: true, comments: [...], total: number, totalPages: number }
 */
export async function GET(req: Request, { params }: Params) {
  try {
    const ctx = await getAuthContext();
    const orgId = requireOrgId(ctx);
    const { id } = await params;

    // B2B 랜딩페이지 소유권 확인
    const page = await prisma.b2BLandingPage.findFirst({
      where: { id, organizationId: orgId },
      select: { id: true },
    });
    if (!page) {
      return NextResponse.json({ ok: false }, { status: 404 });
    }

    // 쿼리 파라미터 파싱
    const { searchParams } = new URL(req.url);
    const skip = Math.max(0, parseInt(searchParams.get('skip') ?? '0') || 0);
    const rawLimit = parseInt(searchParams.get('limit') ?? '10') || 10;
    const limit = Math.min(50, Math.max(1, rawLimit));

    // 전체 댓글 수
    const total = await prisma.b2BLandingComment.count({
      where: { landingPageId: id },
    });

    // 댓글 조회
    const comments = await prisma.b2BLandingComment.findMany({
      where: { landingPageId: id },
      orderBy: { createdAt: 'desc' },
      skip,
      take: limit,
      select: {
        id: true,
        authorName: true,
        content: true,
        isAutoGenerated: true,
        createdAt: true,
      },
    });

    const totalPages = Math.ceil(total / limit);

    logger.log('[GET /api/b2b-landing/[id]/comments]', {
      landingPageId: id,
      orgId,
      skip,
      limit,
      total,
      returned: comments.length,
    });

    return NextResponse.json({
      ok: true,
      comments,
      total,
      totalPages,
    });
  } catch (err) {
    logger.error('[GET /api/b2b-landing/[id]/comments]', { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}
