import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import prisma from "@/lib/prisma";
import { getAuthContext, requireOrgId } from "@/lib/rbac";
import { logger } from "@/lib/logger";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

type Params = { params: Promise<{ id: string }> };

// POST /api/landing-pages/[id]/comments/generate
// body: { count: number } — AI가 실제 후기처럼 댓글 자동 생성
export async function POST(req: Request, { params }: Params) {
  try {
    const ctx   = await getAuthContext();
    const orgId = requireOrgId(ctx);
    const { id } = await params;

    const page = await prisma.crmLandingPage.findFirst({
      where: { id, organizationId: orgId },
      select: { id: true, title: true, htmlContent: true },
    });
    if (!page) return NextResponse.json({ ok: false }, { status: 404 });

    const body = await req.json();
    const count = Math.min(10, Math.max(1, parseInt(body.count ?? "5")));

    // HTML → 텍스트 추출
    const textContent = (page.htmlContent ?? "")
      .replace(/<[^>]*>/g, " ")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 800);

    const prompt = `당신은 크루즈 여행 경험자입니다.
다음은 크루즈 여행 랜딩페이지 내용입니다:
"""
제목: ${page.title}
${textContent}
"""

이 랜딩페이지에 맞는 실제 고객 후기처럼 보이는 댓글 ${count}개를 JSON 배열로 생성하세요.

규칙:
- 각 댓글은 {"authorName": "이름", "content": "내용"} 형식
- authorName: 실제 한국 이름처럼 (예: 김미영, 박준호 등) — 성씨 + 이름 2~3글자
- content: 50~120자, 자연스럽고 구체적인 후기
- 크루즈 관련 경험, 감동, 추천 포함
- 마케팅 문구처럼 보이지 않게, 실제 사람이 쓴 느낌
- JSON 배열만 반환 (다른 텍스트 없음)`;

    const message = await anthropic.messages.create({
      model:      "claude-haiku-4-5-20251001",
      max_tokens: 1024,
      messages:   [{ role: "user", content: prompt }],
    });

    const raw = (message.content[0] as { type: string; text: string }).text.trim();

    // JSON 파싱
    const jsonMatch = raw.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      logger.error("[generate comments] JSON 파싱 실패", { raw: raw.slice(0, 200) });
      return NextResponse.json({ ok: false, message: "AI 응답 파싱 실패" }, { status: 500 });
    }

    const generated = JSON.parse(jsonMatch[0]) as { authorName: string; content: string }[];

    // DB 저장
    const created = await prisma.$transaction(
      generated.map((c) =>
        prisma.crmLandingComment.create({
          data: {
            landingPageId:   page.id,
            authorName:      c.authorName,
            content:         c.content,
            isAutoGenerated: true,
          },
          select: { id: true, authorName: true, content: true, createdAt: true },
        })
      )
    );

    logger.log("[POST /api/landing-pages/[id]/comments/generate]", {
      landingPageId: id, count: created.length, orgId,
    });

    return NextResponse.json({ ok: true, comments: created });
  } catch (err) {
    logger.error("[POST /api/landing-pages/[id]/comments/generate]", { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}
