import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import prisma from "@/lib/prisma";
import { getAuthContext, resolveOrgId, canManageSettings } from "@/lib/rbac";
import { logger } from "@/lib/logger";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

type Params = { params: Promise<{ id: string }> };

// POST /api/landing-pages/[id]/comments/generate
// body: { count: number } — AI가 "자주 묻는 질문 + 운영자 정직한 답변(FAQ)"을 운영자 명의로 시드.
//   ⚠️ 가짜 소비자 후기(허위 신원·추천) 생성 금지 — 표시광고법 안전을 위해 운영자 Q&A로만.
export async function POST(req: Request, { params }: Params) {
  try {
    const ctx   = await getAuthContext();
    // 랜딩 AI 생성(비용 발생)은 지사장(OWNER)·시스템관리자(GLOBAL_ADMIN) 전용 (P0-2)
    if (!canManageSettings(ctx)) {
      return NextResponse.json({ ok: false, message: '권한이 없습니다.' }, { status: 403 });
    }
    const orgId = resolveOrgId(ctx);
    const { id } = await params;

    const page = await prisma.crmLandingPage.findFirst({
      where: { id, organizationId: orgId },
      select: { id: true, title: true, htmlContent: true },
    });
    if (!page) return NextResponse.json({ ok: false }, { status: 404 });

    const body = await req.json();
    const count = Math.min(10, Math.max(1, parseInt(String(body.count ?? "5"), 10)));

    // HTML → 텍스트 추출
    const textContent = (page.htmlContent ?? "")
      .replace(/<[^>]*>/g, " ")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 800);

    const prompt = `당신은 크루즈 여행 상담 운영자입니다.
다음은 크루즈 여행 랜딩페이지 내용입니다:
"""
제목: ${page.title}
${textContent}
"""

이 상품에 대해 방문자가 자주 궁금해할 질문과, 운영자가 "다관점으로" 정직하게 답하는 답변 ${count}쌍을 JSON 배열로 만드세요.

규칙:
- 각 항목은 {"question": "질문", "answer": "답변"} 형식
- question: 실제 방문자가 물어볼 법한 구체적 질문 (예: "멀미가 심한데 괜찮을까요?", "환불 규정이 어떻게 되나요?")
- answer: 운영자가 다관점으로 정직하게 답변 (60~180자). 반드시 (1)좋은 점/장점과 (2)솔직한 주의·한계·"이런 분께는 안 맞을 수 있어요"를 균형 있게 함께 담을 것
- 긍정 일색 금지 — 비판적·신중한 관점도 솔직히 담아 신뢰 형성. 과장·허위 보장 절대 금지, 사실 위주
- 절대 가짜 고객 후기/추천/가짜 방문자 대화를 만들지 말 것 — 운영자 명의 Q&A(다관점)만. 나머지 티키타카는 실제 방문자가 답글로 채웁니다
- JSON 배열만 반환 (다른 텍스트 없음)`;

    const message = await anthropic.messages.create({
      model:      "claude-haiku-4-5-20251001",
      max_tokens: 1500,
      messages:   [{ role: "user", content: prompt }],
    });

    const raw = (message.content[0] as { type: string; text: string }).text.trim();

    // JSON 파싱
    const jsonMatch = raw.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      logger.error("[generate comments] JSON 파싱 실패", { raw: raw.slice(0, 200) });
      return NextResponse.json({ ok: false, message: "AI 응답 파싱 실패" }, { status: 500 });
    }

    const generated = JSON.parse(jsonMatch[0]) as { question: string; answer: string }[];

    // DB 저장 — 각 쌍을 [질문(운영자 시드) + 운영자 답글] 스레드로. 모두 authorRole='operator'(가짜 소비자 신원 없음).
    const created = await prisma.$transaction(async (tx) => {
      const out: Array<{ id: string; authorName: string; content: string; createdAt: Date }> = [];
      for (const qa of generated) {
        if (!qa?.question?.trim() || !qa?.answer?.trim()) continue;
        const q = await tx.crmLandingComment.create({
          data: {
            landingPageId: page.id, authorName: '자주 묻는 질문', content: qa.question.trim(),
            isAutoGenerated: true, authorRole: 'operator', parentId: null,
          },
          select: { id: true, authorName: true, content: true, createdAt: true },
        });
        const a = await tx.crmLandingComment.create({
          data: {
            landingPageId: page.id, authorName: '운영자', content: qa.answer.trim(),
            isAutoGenerated: true, authorRole: 'operator', parentId: q.id,
          },
          select: { id: true, authorName: true, content: true, createdAt: true },
        });
        out.push(q, a);
      }
      return out;
    });

    logger.log("[POST /api/landing-pages/[id]/comments/generate]", {
      landingPageId: id, count: created.length, orgId,
    });

    return NextResponse.json({ ok: true, comments: created });
  } catch (err) {
    logger.error("[POST /api/landing-pages/[id]/comments/generate]", { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}
