import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import prisma from "@/lib/prisma";
import { getAuthContext, resolveOrgId, canManageSettings } from "@/lib/rbac";
import { logger } from "@/lib/logger";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

type Params = { params: Promise<{ id: string }> };

// POST /api/landing-pages/[id]/comments/generate
// body: { count: number } — AI가 커뮤니티 댓글(질문·고민·경험·응원 + 답글)을 유튜브 댓글처럼 랜덤 생성.
//   운영자 전용 도구. 생성물은 운영자가 검토·삭제 가능(isAutoGenerated 표시). 생성 책임은 운영자.
//   ※ 표시광고법: 가공된 소비자 후기 게시 리스크는 사장님 결정·기록됨([[live-issues-round2-20260629]]).
export async function POST(req: Request, { params }: Params) {
  try {
    const ctx   = await getAuthContext();
    // 랜딩 AI 생성(비용 발생)은 지사장(OWNER)·시스템관리자(GLOBAL_ADMIN) 전용 (P0-2)
    if (!canManageSettings(ctx)) {
      return NextResponse.json({ ok: false, message: '권한이 없습니다.' }, { status: 403 });
    }
    const orgId = resolveOrgId(ctx);
    const { id } = await params;

    const page = await prisma.crmLandingPage.findFirst({
      where: { id, organizationId: orgId },
      select: { id: true, title: true, htmlContent: true },
    });
    if (!page) return NextResponse.json({ ok: false }, { status: 404 });

    const body = await req.json();
    const count = Math.min(10, Math.max(1, parseInt(String(body.count ?? "5"), 10)));

    // 작성 기간 — 생성 댓글의 createdAt을 이 범위에 랜덤 분산(오래전부터 쌓인 것처럼 자연스럽게).
    const nowMs = Date.now();
    const parseYmd = (s: unknown, fallback: number): number => {
      const t = Date.parse(String(s ?? ''));
      return Number.isNaN(t) ? fallback : t;
    };
    let fromMs = parseYmd(body.dateFrom, nowMs - 60 * 86_400_000); // 기본 60일 전
    let toMs = Math.min(parseYmd(body.dateTo, nowMs), nowMs);       // 미래 날짜 방지
    if (fromMs > toMs) fromMs = toMs;
    const randInRange = (loMs: number) => new Date(loMs + Math.floor(Math.random() * Math.max(1, toMs - loMs + 1)));

    // HTML → 텍스트 추출
    const textContent = (page.htmlContent ?? "")
      .replace(/<[^>]*>/g, " ")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 800);

    const prompt = `당신은 크루즈/여행 커뮤니티 게시판의 다양한 방문자들입니다.
다음 랜딩페이지 상품에 대해, 실제 커뮤니티처럼 자연스러운 댓글 대화 ${count}개 묶음(스레드)을 JSON 배열로 만드세요.
"""
제목: ${page.title}
${textContent}
"""

규칙:
- 각 스레드: {"author":"닉네임","content":"댓글","replies":[{"author":"닉네임","content":"답글"}]}
- 댓글 종류를 다양하게 섞기: 질문("이거 멀미 심한데 괜찮나요?"), 고민("처음이라 좀 어렵더라고요"), 경험공유("저 다녀와봤는데 ~한 점이 좋았어요"), 공감·응원("저도 궁금해요","잘 되면 좋겠네요")
- 닉네임: 캐주얼하고 다양하게 (예: 여행조아, 바다사랑, 부산댁, 초보맘, 김** 등) — 매번 다르게
- 말투: 유튜브 댓글처럼 짧고 자연스럽게. 과장 광고 문구·"강력추천" 남발 금지
- replies는 0~2개, 대화가 자연스럽게 이어지게(다른 방문자가 답하거나 경험 보태기)
- 매번 새롭게 랜덤하게, 서로 다른 주제·말투로
- JSON 배열만 반환 (다른 텍스트 없음)`;

    const message = await anthropic.messages.create({
      model:       "claude-haiku-4-5-20251001",
      max_tokens:  2000,
      temperature: 1, // 매번 다양·랜덤하게
      messages:    [{ role: "user", content: prompt }],
    });

    const raw = (message.content[0] as { type: string; text: string }).text.trim();

    // JSON 파싱
    const jsonMatch = raw.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      logger.error("[generate comments] JSON 파싱 실패", { raw: raw.slice(0, 200) });
      return NextResponse.json({ ok: false, message: "AI 응답 파싱 실패" }, { status: 500 });
    }

    type GenReply = { author?: string; content?: string };
    type GenThread = { author?: string; content?: string; replies?: GenReply[] };
    const threads = JSON.parse(jsonMatch[0]) as GenThread[];
    const clip = (s: string, n: number) => s.trim().slice(0, n);

    // DB 저장 — 스레드를 [방문자 댓글 + 방문자 답글]로. authorRole='visitor'(커뮤니티 댓글).
    const created = await prisma.$transaction(async (tx) => {
      const out: Array<{ id: string; authorName: string; content: string; createdAt: Date }> = [];
      for (const t of threads) {
        if (!t?.author?.trim() || !t?.content?.trim()) continue;
        const qDate = randInRange(fromMs); // 질문은 기간 내 임의 시점
        const q = await tx.crmLandingComment.create({
          data: {
            landingPageId: page.id, authorName: clip(t.author, 30), content: clip(t.content, 500),
            isAutoGenerated: true, authorRole: 'visitor', parentId: null,
            createdAt: qDate,
          },
          select: { id: true, authorName: true, content: true, createdAt: true },
        });
        out.push(q);
        for (const r of (t.replies ?? []).slice(0, 3)) {
          if (!r?.author?.trim() || !r?.content?.trim()) continue;
          const a = await tx.crmLandingComment.create({
            data: {
              landingPageId: page.id, authorName: clip(r.author, 30), content: clip(r.content, 500),
              isAutoGenerated: true, authorRole: 'visitor', parentId: q.id,
              createdAt: randInRange(qDate.getTime()), // 답글은 질문 이후~기간끝 사이
            },
            select: { id: true, authorName: true, content: true, createdAt: true },
          });
          out.push(a);
        }
      }
      return out;
    });

    logger.log("[POST /api/landing-pages/[id]/comments/generate]", {
      landingPageId: id, count: created.length, orgId,
    });

    return NextResponse.json({ ok: true, comments: created });
  } catch (err) {
    logger.error("[POST /api/landing-pages/[id]/comments/generate]", { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}
