'use client';

import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';

interface Comment {
  id: number;
  authorName: string;
  content: string;
  createdAt: string;
  isAutoGenerated?: boolean;
  isMine?: boolean; // 본인 댓글 여부
}

interface LandingCommentListProps {
  comments: Comment[];
  slug: string;
  onCommentUpdated?: () => void;
  isLandingPageOwner?: boolean; // 랜딩페이지 소유자 여부
  isBossUser?: boolean; // boss 사용자 여부
}

export function LandingCommentList({ comments, slug, onCommentUpdated, isLandingPageOwner = false, isBossUser = false }: LandingCommentListProps) {
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editContent, setEditContent] = useState('');
  const [editPassword, setEditPassword] = useState('');
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const [deletePassword, setDeletePassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [canDelete, setCanDelete] = useState(false); // 관리자/대리점장 여부
  
  // 권한 상태 변경 감지 (디버깅 용도 제거됨)

  // 관리자/대리점장/boss 사용자 권한 확인
  useEffect(() => {
    const checkPermission = async () => {
      try {
        const response = await fetch('/api/auth/me', {
          credentials: 'include',
        });
        if (response.ok) {
          const data = await response.json();
          if (data.ok && data.user) {
            // 관리자 또는 대리점장인지 확인
            const isAdmin = data.user.role === 'admin';
            // AffiliateProfile 또는 affiliateProfile 모두 체크 (대소문자 구분 없음)
            const affiliateProfile = data.user.AffiliateProfile || data.user.affiliateProfile;
            const isBranchManager = data.user.role === 'partner' && affiliateProfile?.type === 'BRANCH_MANAGER';
            // boss로 시작하는 사용자명/이메일 체크
            const userName = (data.user.name || '').toLowerCase();
            const userEmail = (data.user.email || '').toLowerCase();
            const isBossUserFromApi = userName.startsWith('boss') || userEmail.startsWith('boss');
            // 관리자는 모든 랜딩페이지 댓글 삭제 가능, 대리점장/boss는 자신의 랜딩페이지만 (절대!)
            // isLandingPageOwner는 대리점장의 경우만 true, 관리자는 항상 삭제 가능
            const canDeleteValue = isAdmin || (isBranchManager && isLandingPageOwner) || (isBossUserFromApi && isLandingPageOwner) || isBossUser;
            setCanDelete(canDeleteValue);
          }
        }
      } catch {
        // 권한 확인 실패 시에도 prop으로 전달된 isBossUser는 사용
        setCanDelete(isBossUser);
      }
    };
    checkPermission();
  }, [isBossUser, isLandingPageOwner]);

  const handleEdit = (comment: Comment) => {
    if (comment.isAutoGenerated) {
      alert('AI 생성 댓글은 수정할 수 없습니다.');
      return;
    }
    setEditingId(comment.id);
    setEditContent(comment.content);
    setEditPassword('');
    setError(null);
  };

  const handleCancelEdit = () => {
    setEditingId(null);
    setEditContent('');
    setEditPassword('');
    setError(null);
  };

  const handleSubmitEdit = async (commentId: number) => {
    if (!editContent.trim() || !editPassword.trim()) {
      setError('내용과 비밀번호를 모두 입력해주세요.');
      return;
    }

    setIsSubmitting(true);
    setError(null);

    try {
      const response = await fetch(`/api/public/landing-pages/${slug}/comments/${commentId}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          content: editContent.trim(),
          password: editPassword.trim(),
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.ok) {
        throw new Error(data.error || '댓글 수정에 실패했습니다.');
      }

      setEditingId(null);
      setEditContent('');
      setEditPassword('');
      
      if (onCommentUpdated) {
        onCommentUpdated();
      } else {
        window.location.reload();
      }
    } catch (submissionError) {
      setError(
        submissionError instanceof Error ? submissionError.message : '댓글 수정 중 오류가 발생했습니다.'
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDelete = async (commentId: number) => {
    // 추가 권한 확인을 위한 최신 사용자 정보 가져오기
    let latestCanDelete = canDelete;
    let latestIsOwner = isLandingPageOwner;
    
    try {
      const meResponse = await fetch('/api/auth/me', { credentials: 'include' });
      if (meResponse.ok) {
        const meData = await meResponse.json();
        if (meData.ok && meData.user) {
          const isAdmin = meData.user.role === 'admin';
          const affiliateProfile = meData.user.AffiliateProfile || meData.user.affiliateProfile;
          const isBranchManager = meData.user.role === 'partner' && affiliateProfile?.type === 'BRANCH_MANAGER';
          const userName = (meData.user.name || '').toLowerCase();
          const userEmail = (meData.user.email || '').toLowerCase();
          const isBossUserFromApi = userName.startsWith('boss') || userEmail.startsWith('boss');
          
          // 관리자는 모든 랜딩페이지 댓글 삭제 가능, 대리점장/boss는 자신의 랜딩페이지만
          if (isAdmin) {
            latestCanDelete = true; // 관리자는 항상 삭제 가능
            latestIsOwner = true; // 관리자는 소유자로 인정
          } else if (isBranchManager || isBossUserFromApi) {
            // 대리점장/boss는 자신의 랜딩페이지일 때만 삭제 가능
            latestCanDelete = (isBranchManager || isBossUserFromApi) && (isLandingPageOwner || canDelete);
            if (latestCanDelete) {
              latestIsOwner = true; // 대리점장/boss는 자신의 랜딩페이지일 때만 소유자로 인정
            }
          } else {
            latestCanDelete = canDelete;
          }
        }
      }
    } catch {
      // 권한 재확인 실패 시 기존 canDelete 값 사용
    }
    
    // 대리점장/관리자/boss는 비밀번호 없이 바로 삭제 (절대 모달 띄우지 않음)
    // 관리자는 항상 삭제 가능, 대리점장/boss는 자신의 랜딩페이지일 때만
    const canDeleteWithoutPassword = latestCanDelete || latestIsOwner || isBossUser;
    
    if (canDeleteWithoutPassword) {
      // 확인만 받고 바로 삭제 (비밀번호 모달 절대 띄우지 않음)
      if (!confirm('정말로 이 댓글을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.')) {
        return;
      }
      
      setIsSubmitting(true);
      setError(null);

      try {
        // 비밀번호 없이 삭제 요청 (body에 password 필드 자체를 보내지 않음)
        const response = await fetch(`/api/public/landing-pages/${slug}/comments/${commentId}`, {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json',
          },
          credentials: 'include', // 쿠키 포함 (세션 확인을 위해 필수!)
          body: JSON.stringify({}), // 빈 객체로 보내서 서버에서 권한 확인하도록
        });

        const data = await response.json();

        if (!response.ok || !data.ok) {
          throw new Error(data.error || '댓글 삭제에 실패했습니다.');
        }

        if (onCommentUpdated) {
          onCommentUpdated();
        } else {
          window.location.reload();
        }
      } catch (submissionError) {
        alert(submissionError instanceof Error ? submissionError.message : '댓글 삭제 중 오류가 발생했습니다.');
      } finally {
        setIsSubmitting(false);
      }
    } else {
      // 일반 사용자만 모달로 비밀번호 입력
      setDeleteId(commentId);
      setDeletePassword('');
      setError(null);
    }
  };

  const handleCancelDelete = () => {
    setDeleteId(null);
    setDeletePassword('');
    setError(null);
  };

  const handleConfirmDelete = async (commentId: number) => {
    // 랜딩페이지 소유자/boss/관리자/대리점장은 비밀번호 불필요, 일반 사용자는 비밀번호 필수
    const canDeleteWithoutPassword = isLandingPageOwner || isBossUser || canDelete;
    
    // 대리점장/관리자/boss는 이 함수가 호출되면 안 됨 (handleDelete에서 바로 삭제해야 함)
    // 하지만 혹시 모를 경우를 대비해 여기서도 체크
    if (canDeleteWithoutPassword) {
      // 비밀번호 없이 삭제
      setIsSubmitting(true);
      setError(null);

      try {
        const response = await fetch(`/api/public/landing-pages/${slug}/comments/${commentId}`, {
          method: 'DELETE',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({}), // 빈 객체로 보내서 서버에서 권한 확인하도록
        });

        const data = await response.json();

        if (!response.ok || !data.ok) {
          throw new Error(data.error || '댓글 삭제에 실패했습니다.');
        }

        setDeleteId(null);
        setDeletePassword('');

        if (onCommentUpdated) {
          onCommentUpdated();
        } else {
          window.location.reload();
        }
      } catch (submissionError) {
        setError(
          submissionError instanceof Error ? submissionError.message : '댓글 삭제 중 오류가 발생했습니다.'
        );
      } finally {
        setIsSubmitting(false);
      }
      return;
    }
    
    // 일반 사용자는 비밀번호 필수
    if (!deletePassword.trim()) {
      setError('비밀번호를 입력해주세요.');
      return;
    }

    setIsSubmitting(true);
    setError(null);

    try {
      const response = await fetch(`/api/public/landing-pages/${slug}/comments/${commentId}`, {
        method: 'DELETE',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          password: deletePassword.trim(), // 일반 사용자는 비밀번호 필수
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.ok) {
        throw new Error(data.error || '댓글 삭제에 실패했습니다.');
      }

      setDeleteId(null);
      setDeletePassword('');
      
      if (onCommentUpdated) {
        onCommentUpdated();
      } else {
        window.location.reload();
      }
    } catch (submissionError) {
      setError(
        submissionError instanceof Error ? submissionError.message : '댓글 삭제 중 오류가 발생했습니다.'
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="lp-comment-list">
      {comments.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '24px', color: '#64748b', fontSize: '14px' }}>
          아직 댓글이 없습니다. 첫 번째 댓글을 작성해보세요!
        </div>
      ) : (
        comments.map((comment) => (
        <article key={comment.id} className="lp-comment-card">
          {editingId === comment.id ? (
            <div>
              <div className="lp-form-field">
                <label>
                  댓글 내용 <span className="lp-required">*</span>
                </label>
                <textarea
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  rows={4}
                  style={{
                    width: '100%',
                    borderRadius: '14px',
                    border: '2px solid #e2e8f0',
                    padding: '14px 16px',
                    fontSize: '16px',
                    fontFamily: 'inherit',
                    resize: 'vertical',
                  }}
                />
              </div>
              <div className="lp-form-field">
                <label>
                  비밀번호 <span className="lp-required">*</span>
                </label>
                <input
                  type="password"
                  value={editPassword}
                  onChange={(e) => setEditPassword(e.target.value)}
                  placeholder="댓글 작성 시 입력한 비밀번호"
                  style={{
                    width: '100%',
                    borderRadius: '14px',
                    border: '2px solid #e2e8f0',
                    padding: '14px 16px',
                    fontSize: '16px',
                  }}
                />
              </div>
              {error && (
                <div className="lp-error-message" style={{ color: '#ef4444', fontSize: '14px', marginTop: '8px' }}>
                  {error}
                </div>
              )}
              <div style={{ display: 'flex', gap: '8px', marginTop: '12px' }}>
                <button
                  type="button"
                  onClick={() => handleSubmitEdit(comment.id)}
                  disabled={isSubmitting}
                  className="lp-primary-button"
                  style={{ flex: 1, marginTop: 0 }}
                >
                  {isSubmitting ? '수정 중...' : '수정 완료'}
                </button>
                <button
                  type="button"
                  onClick={handleCancelEdit}
                  disabled={isSubmitting}
                  className="lp-secondary-button"
                  style={{ flex: 1, marginTop: 0 }}
                >
                  취소
                </button>
              </div>
            </div>
          ) : (
            <>
              <div className="lp-comment-meta">
                <span className="lp-comment-author">
                  {comment.authorName}
                </span>
                <span className="lp-comment-date">
                  {new Date(comment.createdAt).toLocaleDateString('ko-KR')}
                </span>
              </div>
              <p className="lp-comment-text">{comment.content}</p>
              <div style={{ display: 'flex', gap: '8px', marginTop: '12px' }}>
                {!comment.isAutoGenerated && (
                  <button
                    type="button"
                    onClick={() => handleEdit(comment)}
                    className="lp-secondary-button"
                    style={{ fontSize: '14px', padding: '8px 16px' }}
                  >
                    수정
                  </button>
                )}
                {/* 삭제 버튼: 대리점장/관리자/boss는 모든 댓글 삭제 가능, 일반 사용자는 본인 댓글만 삭제 가능 */}
                {((isLandingPageOwner || isBossUser || canDelete) ? true : comment.isMine) && (
                  <button
                    type="button"
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      handleDelete(comment.id);
                    }}
                    className="lp-danger-button"
                    style={{ 
                      fontSize: '14px', 
                      padding: '8px 16px',
                      backgroundColor: '#ef4444',
                      color: 'white',
                      border: 'none',
                      borderRadius: '8px',
                      cursor: 'pointer',
                      fontWeight: '500',
                    }}
                  >
                    삭제
                  </button>
                )}
              </div>
            </>
          )}
        </article>
      ))
      )}
      {/* 삭제 확인 모달 - 포털로 body에 렌더링 */}
      {deleteId !== null && typeof window !== 'undefined' && createPortal(
        <div 
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 10000,
          }}
          onClick={handleCancelDelete}
        >
          <div 
            style={{
              backgroundColor: 'white',
              padding: '24px',
              borderRadius: '12px',
              maxWidth: '400px',
              width: '90%',
              boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <h3 style={{ marginBottom: '16px', fontSize: '18px', fontWeight: '600' }}>
              댓글 삭제
            </h3>
            <p style={{ marginBottom: '16px', color: '#64748b', fontSize: '14px' }}>
              정말로 이 댓글을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.
            </p>
            {/* 대리점장/관리자/boss가 아닌 일반 사용자만 비밀번호 입력 필요 */}
            {!(isLandingPageOwner || isBossUser || canDelete) && (
              <div style={{ marginBottom: '16px' }}>
                <label style={{ display: 'block', marginBottom: '8px', fontSize: '14px', fontWeight: '600', color: '#1e293b' }}>
                  비밀번호 <span style={{ color: '#ef4444' }}>*</span>
                </label>
                <input
                  type="password"
                  value={deletePassword}
                  onChange={(e) => setDeletePassword(e.target.value)}
                  placeholder="댓글 작성 시 입력한 비밀번호"
                  style={{
                    width: '100%',
                    borderRadius: '8px',
                    border: '2px solid #e2e8f0',
                    padding: '10px 12px',
                    fontSize: '14px',
                  }}
                />
              </div>
            )}
            {error && (
              <div style={{ color: '#ef4444', fontSize: '14px', marginBottom: '12px' }}>
                {error}
              </div>
            )}
            <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end' }}>
              <button
                type="button"
                onClick={handleCancelDelete}
                disabled={isSubmitting}
                style={{
                  padding: '8px 16px',
                  border: '2px solid #e2e8f0',
                  borderRadius: '8px',
                  backgroundColor: 'white',
                  color: '#64748b',
                  cursor: isSubmitting ? 'not-allowed' : 'pointer',
                  fontSize: '14px',
                  fontWeight: '500',
                }}
              >
                취소
              </button>
              <button
                type="button"
                onClick={() => handleConfirmDelete(deleteId)}
                disabled={isSubmitting}
                style={{
                  padding: '8px 16px',
                  border: 'none',
                  borderRadius: '8px',
                  backgroundColor: '#ef4444',
                  color: 'white',
                  cursor: isSubmitting ? 'not-allowed' : 'pointer',
                  fontSize: '14px',
                  fontWeight: '500',
                }}
              >
                {isSubmitting ? '삭제 중...' : '삭제'}
              </button>
            </div>
          </div>
        </div>,
        document.body
      )}
    </div>
  );
}

