'use client';

import { useState, useEffect, useCallback } from 'react';
import { useRouter, useParams } from 'next/navigation';
import {
  ArrowLeft, Save, RefreshCw, Users, MessageSquare, BarChart2,
  Trash2, Sparkles, ChevronDown, Eye, Phone, Mail, Calendar,
  Tag, Loader2,
} from 'lucide-react';

// ── Types ──────────────────────────────────────────────────────

type Registration = {
  id: string;
  name: string;
  phone: string;
  email: string | null;
  utmSource: string | null;
  funnelStarted: boolean;
  createdAt: string;
};

type Comment = {
  id: string;
  authorName: string;
  content: string;
  isAutoGenerated: boolean;
  createdAt: string;
};

type PageDetail = {
  id: string;
  title: string;
  slug: string;
  htmlContent: string | null;
  isActive: boolean;
  editorMode: string;
  viewCount: number;
  partnerId: string | null;
  formConfig: Record<string, unknown> | null;
  buttonTitle: string | null;
  groupId: string | null;
  autoFunnelId: string | null;
  paymentEnabled: boolean;
  paymentType: string | null;
  productName: string | null;
  productPrice: number | null;
  cycleDay: number | null;
  expireDate: string | null;
  commentEnabled: boolean;
  regEmailEnabled: boolean;
  regEmailSubject: string | null;
  regEmailContent: string | null;
  exposureTitle: string | null;
  exposureImage: string | null;
  footerText: string | null;
  headerScript: string | null;
  completionPageUrl: string | null;
  description: string | null;
  registrations: Registration[];
  comments: Comment[];
};

type FunnelStats = {
  viewCount: number;
  registered: number;
  funnelEntered: number;
  visitToRegister: number;
  registerToFunnel: number;
};

type TabKey = 'editor' | 'registrations' | 'comments' | 'stats';

// ── Helpers ────────────────────────────────────────────────────
const maskPhone = (p: string) => p.length < 7 ? p : p.slice(0, 3) + '-****-' + p.slice(-4);
const fmtDate = (iso: string) => new Date(iso).toLocaleDateString('ko-KR', { year: 'numeric', month: '2-digit', day: '2-digit' });
const inputCls = 'w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent';

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <label className="block text-xs font-medium text-gray-500 mb-1">{label}</label>
      {children}
    </div>
  );
}

// ── Page Component ─────────────────────────────────────────────
export default function B2BEditorEditPage() {
  const router = useRouter();
  const { id } = useParams() as { id: string };

  // Tab state
  const [tab, setTab] = useState<TabKey>('editor');

  // Page detail
  const [page, setPage] = useState<PageDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  // Editor fields - basic
  const [title, setTitle] = useState('');
  const [slug, setSlug] = useState('');
  const [html, setHtml] = useState('');
  const [isActive, setIsActive] = useState(true);

  // Editor fields - form settings
  const [buttonTitle, setButtonTitle] = useState('');
  const [completionPageUrl, setCompletionPageUrl] = useState('');
  const [footerText, setFooterText] = useState('');

  // ✨ NEW: 카테고리 관리
  const [category, setCategory] = useState('');
  const [categories, setCategories] = useState<string[]>([]);
  const [newCategoryInput, setNewCategoryInput] = useState('');

  // Editor fields - SEO / exposure
  const [exposureTitle, setExposureTitle] = useState('');
  const [exposureImage, setExposureImage] = useState('');
  const [description, setDescription] = useState('');
  const [headerScript, setHeaderScript] = useState('');

  // Editor fields - comments
  const [commentEnabled, setCommentEnabled] = useState(false);

  // Editor fields - payment
  const [paymentEnabled, setPaymentEnabled] = useState(false);
  const [paymentType, setPaymentType] = useState('onetime');
  const [productName, setProductName] = useState('');
  const [productPrice, setProductPrice] = useState('');
  const [cycleDay, setCycleDay] = useState('1');
  const [expireDate, setExpireDate] = useState('');

  // Editor fields - email
  const [regEmailEnabled, setRegEmailEnabled] = useState(false);
  const [regEmailSubject, setRegEmailSubject] = useState('');
  const [regEmailContent, setRegEmailContent] = useState('');

  // Save state
  const [saving, setSaving] = useState(false);
  const [saveMsg, setSaveMsg] = useState('');

  // Comments tab state
  const [comments, setComments] = useState<Comment[]>([]);
  const [generating, setGenerating] = useState(false);
  const [genDropdownOpen, setGenDropdownOpen] = useState(false);
  const [commentMsg, setCommentMsg] = useState('');

  // Stats tab state
  const [stats, setStats] = useState<FunnelStats | null>(null);
  const [statsLoading, setStatsLoading] = useState(false);

  // Registrations tab state
  const [registrations, setRegistrations] = useState<Registration[]>([]);

  // ── Load page detail ─────────────────────────────────────────

  const loadPage = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const res = await fetch(`/api/b2b-landing/${id}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      if (!data.ok || !data.page) {
        throw new Error(data.message || '페이지를 불러올 수 없습니다.');
      }

      const p = data.page as PageDetail;
      setPage(p);

      // Basic fields
      setTitle(p.title);
      setSlug(p.slug);
      setHtml(p.htmlContent ?? '');
      setIsActive(p.isActive);

      // Form settings
      setButtonTitle(p.buttonTitle ?? '');
      setCompletionPageUrl(p.completionPageUrl ?? '');
      setFooterText(p.footerText ?? '');

      // SEO / exposure
      setExposureTitle(p.exposureTitle ?? '');
      setExposureImage(p.exposureImage ?? '');
      setDescription(p.description ?? '');
      setHeaderScript(p.headerScript ?? '');

      // Comments
      setCommentEnabled(p.commentEnabled);

      // Payment
      setPaymentEnabled(p.paymentEnabled);
      setPaymentType(p.paymentType ?? 'onetime');
      setProductName(p.productName ?? '');
      setProductPrice(p.productPrice ? String(p.productPrice) : '');
      setCycleDay(p.cycleDay ? String(p.cycleDay) : '1');
      setExpireDate(p.expireDate ? p.expireDate.split('T')[0] : '');

      // Email
      setRegEmailEnabled(p.regEmailEnabled);
      setRegEmailSubject(p.regEmailSubject ?? '');
      setRegEmailContent(p.regEmailContent ?? '');

      // ✨ NEW: 카테고리
      setCategory(p.category ?? '');

      // Related data
      setRegistrations(p.registrations ?? []);
      setComments(p.comments ?? []);
    } catch (err) {
      setError(err instanceof Error ? err.message : '로딩 실패');
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    loadPage();
  }, [loadPage]);

  // ✨ NEW: 카테고리 목록 로드
  useEffect(() => {
    const loadCategories = async () => {
      try {
        // org ID를 가져오려면 page 데이터가 필요
        if (!page?.organizationId) return;

        const res = await fetch(`/api/b2b-landing/categories?orgId=${page.organizationId}`);
        if (res.ok) {
          const data = await res.json();
          const catNames = data.data?.categories?.map((c: { name: string }) => c.name) || [];
          setCategories(catNames);
        }
      } catch (err) {
        console.error('카테고리 로드 실패:', err);
      }
    };

    loadCategories();
  }, [page?.organizationId]);

  // Clear save message after 2s
  useEffect(() => {
    if (!saveMsg) return;
    const t = setTimeout(() => setSaveMsg(''), 2000);
    return () => clearTimeout(t);
  }, [saveMsg]);

  // Clear comment message after 3s
  useEffect(() => {
    if (!commentMsg) return;
    const t = setTimeout(() => setCommentMsg(''), 3000);
    return () => clearTimeout(t);
  }, [commentMsg]);

  // ── Save ─────────────────────────────────────────────────────

  const handleSave = async () => {
    if (!title.trim()) {
      setError('제목을 입력하세요.');
      return;
    }
    setSaving(true);
    setError('');
    setSaveMsg('');

    try {
      // Build payment payload only if enabled
      const paymentPayload = paymentEnabled
        ? {
            paymentType,
            productName: productName || null,
            productPrice: parseInt(productPrice) || null,
            ...(paymentType === 'subscription'
              ? { cycleDay: parseInt(cycleDay), expireDate: expireDate || null }
              : {}),
          }
        : {};

      const res = await fetch(`/api/b2b-landing/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          slug: slug || undefined,
          htmlContent: html,
          isActive,
          buttonTitle: buttonTitle || null,
          exposureTitle: exposureTitle || null,
          exposureImage: exposureImage || null,
          description: description || null,
          footerText: footerText || null,
          headerScript: headerScript || null,
          completionPageUrl: completionPageUrl || null,
          category: category || null,
          commentEnabled,
          paymentEnabled,
          ...paymentPayload,
          regEmailEnabled,
          regEmailSubject: regEmailSubject || null,
          regEmailContent: regEmailContent || null,
        }),
      });

      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      if (!data.ok) throw new Error(data.message || '저장 실패');

      setSaveMsg('저장 완료!');
    } catch (err) {
      setError(`저장 실패: ${err instanceof Error ? err.message : '알 수 없음'}`);
    } finally {
      setSaving(false);
    }
  };

  // ── Comments ─────────────────────────────────────────────────

  const generateComments = async (count: number) => {
    setGenerating(true);
    setCommentMsg('');
    setGenDropdownOpen(false);

    try {
      const res = await fetch(`/api/b2b-landing/${id}/comments`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ generate: true, count }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);

      const data = await res.json();
      if (data.ok && data.comments) {
        setComments((prev) => [...data.comments, ...prev]);
        setCommentMsg(`${data.comments.length}개 AI 후기 생성 완료`);
      } else {
        throw new Error(data.message || '생성 실패');
      }
    } catch (err) {
      setCommentMsg(
        `생성 실패: ${err instanceof Error ? err.message : '알 수 없음'}`
      );
    } finally {
      setGenerating(false);
    }
  };

  const deleteComment = async (commentId: string) => {
    if (!confirm('이 후기를 삭제하시겠습니까?')) return;

    try {
      const res = await fetch(
        `/api/b2b-landing/${id}/comments?commentId=${encodeURIComponent(commentId)}`,
        { method: 'DELETE' }
      );
      if (!res.ok) throw new Error(`HTTP ${res.status}`);

      const data = await res.json();
      if (data.ok) {
        setComments((prev) => prev.filter((c) => c.id !== commentId));
      } else {
        throw new Error(data.message || '삭제 실패');
      }
    } catch (err) {
      setCommentMsg(
        `삭제 실패: ${err instanceof Error ? err.message : '알 수 없음'}`
      );
    }
  };

  // ── Stats ────────────────────────────────────────────────────

  const loadStats = useCallback(async () => {
    setStatsLoading(true);
    try {
      const res = await fetch(`/api/b2b-landing/${id}/stats`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      if (data.ok) {
        setStats(data.stats);
      } else {
        throw new Error(data.message || '통계 로딩 실패');
      }
    } catch {
      setStats(null);
    } finally {
      setStatsLoading(false);
    }
  }, [id]);

  useEffect(() => {
    if (tab === 'stats') loadStats();
  }, [tab, loadStats]);

  // ── Loading / Error states ───────────────────────────────────

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen bg-gray-50">
        <div className="flex flex-col items-center gap-3">
          <Loader2 className="w-8 h-8 text-gray-400 animate-spin" />
          <p className="text-sm text-gray-500">페이지 로딩 중...</p>
        </div>
      </div>
    );
  }

  if (!page && error) {
    return (
      <div className="flex items-center justify-center h-screen bg-gray-50">
        <div className="text-center">
          <p className="text-red-500 mb-4">{error}</p>
          <button
            onClick={() => router.back()}
            className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg text-sm hover:bg-gray-300"
          >
            돌아가기
          </button>
        </div>
      </div>
    );
  }

  // ── Tab config ───────────────────────────────────────────────

  const tabCfg: {
    key: TabKey;
    label: string;
    icon: React.ReactNode;
    badge?: number;
  }[] = [
    { key: 'editor', label: '편집', icon: <Eye className="w-3.5 h-3.5" /> },
    {
      key: 'registrations',
      label: '등록자',
      icon: <Users className="w-3.5 h-3.5" />,
      badge: registrations.length,
    },
    {
      key: 'comments',
      label: '후기',
      icon: <MessageSquare className="w-3.5 h-3.5" />,
      badge: comments.length,
    },
    { key: 'stats', label: '통계', icon: <BarChart2 className="w-3.5 h-3.5" /> },
  ];

  return (
    <div className="flex flex-col h-screen bg-gray-50">
      {/* ── Header ── */}
      <div className="flex items-center gap-3 px-4 py-3 bg-white border-b border-gray-200 shrink-0">
        <button onClick={() => router.back()} className="text-gray-400 hover:text-gray-700"><ArrowLeft className="w-5 h-5" /></button>
        <h1 className="text-base font-semibold text-gray-800 truncate max-w-[200px]">{title || '제목 없음'}</h1>
        <div className="flex border border-gray-200 rounded-lg overflow-hidden text-xs ml-2">
          {tabCfg.map((t) => (
            <button key={t.key} onClick={() => setTab(t.key)}
              className={`px-3 py-1.5 font-medium flex items-center gap-1 transition-colors ${tab === t.key ? 'bg-gray-900 text-white' : 'text-gray-500 hover:bg-gray-50'}`}>
              {t.icon} {t.label}
              {t.badge != null && t.badge > 0 && (
                <span className={`ml-0.5 px-1.5 py-0.5 rounded-full text-[10px] font-bold ${tab === t.key ? 'bg-white/20 text-white' : 'bg-gray-100 text-gray-600'}`}>{t.badge}</span>
              )}
            </button>
          ))}
        </div>
        <div className="flex-1" />
        {error && <span className="text-xs text-red-500 max-w-[200px] truncate">{error}</span>}
        {saveMsg && <span className="text-xs text-green-600 font-medium">{saveMsg}</span>}
        {tab === 'editor' && (
          <button onClick={handleSave} disabled={saving}
            className="flex items-center gap-1.5 bg-gray-900 text-white px-4 py-1.5 rounded-lg text-sm font-medium disabled:opacity-50 hover:bg-gray-800">
            {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
            {saving ? '저장 중...' : '저장'}
          </button>
        )}
      </div>

      {/* ── Tab 1: Editor ── */}
      {tab === 'editor' && (
        <div className="flex-1 flex overflow-hidden">
          {/* Left: Editor */}
          <div className="flex-1 overflow-y-auto border-r border-gray-200 bg-white">
            <div className="max-w-2xl mx-auto p-6 space-y-6">
              {/* Basic info */}
              <section className="space-y-4">
                <h2 className="text-sm font-semibold text-gray-700 border-b border-gray-100 pb-2">기본 정보</h2>
                <div className="grid grid-cols-2 gap-4">
                  <Field label="제목"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="랜딩페이지 제목" className={inputCls} /></Field>
                  <Field label="슬러그"><input value={slug} onChange={(e) => setSlug(e.target.value)} placeholder="url-slug" className={`${inputCls} font-mono`} /></Field>
                </div>

                {/* ✨ NEW: 카테고리 드롭다운 */}
                <div className="grid grid-cols-2 gap-4">
                  <Field label="카테고리">
                    <div className="flex gap-2">
                      <select
                        value={category}
                        onChange={(e) => setCategory(e.target.value)}
                        className={`flex-1 ${inputCls}`}
                      >
                        <option value="">선택 안 함</option>
                        {categories.map((cat) => (
                          <option key={cat} value={cat}>
                            {cat}
                          </option>
                        ))}
                      </select>
                      <button
                        onClick={() => {
                          const newCat = prompt('새 카테고리 이름:');
                          if (newCat && page?.organizationId) {
                            fetch('/api/b2b-landing/categories', {
                              method: 'POST',
                              headers: { 'Content-Type': 'application/json' },
                              body: JSON.stringify({
                                orgId: page.organizationId,
                                name: newCat,
                              }),
                            })
                              .then((res) => res.json())
                              .then((data) => {
                                if (data.ok) {
                                  setCategories([...categories, newCat]);
                                  setCategory(newCat);
                                } else {
                                  alert(`추가 실패: ${data.message}`);
                                }
                              })
                              .catch((err) => alert(`오류: ${err.message}`));
                          }
                        }}
                        className="px-3 py-2 bg-blue-600 text-white rounded text-sm hover:bg-blue-700 shrink-0"
                      >
                        + 새로
                      </button>
                    </div>
                  </Field>
                </div>

                <div className="flex items-center gap-4">
                  <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
                    <input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} className="w-4 h-4 rounded border-gray-300" /> ✅ 활성 (보여짐)
                  </label>
                  <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
                    <input type="checkbox" checked={commentEnabled} onChange={(e) => setCommentEnabled(e.target.checked)} className="w-4 h-4 rounded border-gray-300" /> 후기 표시
                  </label>
                </div>
              </section>

              {/* HTML Content */}
              <section className="space-y-3">
                <h2 className="text-sm font-semibold text-gray-700 border-b border-gray-100 pb-2">HTML 콘텐츠</h2>
                <textarea value={html} onChange={(e) => setHtml(e.target.value)}
                  className="w-full h-[400px] font-mono text-xs p-4 border border-gray-200 rounded-lg bg-gray-900 text-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500 resize-y"
                  spellCheck={false} placeholder="HTML 코드를 입력하세요..." />
              </section>

              {/* Form settings */}
              <section className="space-y-4">
                <h2 className="text-sm font-semibold text-gray-700 border-b border-gray-100 pb-2">신청 폼 설정</h2>
                <div className="grid grid-cols-2 gap-4">
                  <Field label="신청 버튼 이름"><input value={buttonTitle} onChange={(e) => setButtonTitle(e.target.value)} placeholder="신청하기" className={inputCls} /></Field>
                  <Field label="완료 후 이동 URL"><input value={completionPageUrl} onChange={(e) => setCompletionPageUrl(e.target.value)} placeholder="https://..." className={inputCls} /></Field>
                </div>
                <Field label="폼 하단 텍스트"><input value={footerText} onChange={(e) => setFooterText(e.target.value)} placeholder="예: 개인정보 수집에 동의합니다" className={inputCls} /></Field>
              </section>

              {/* SEO / Exposure */}
              <section className="space-y-4">
                <h2 className="text-sm font-semibold text-gray-700 border-b border-gray-100 pb-2">노출 설정 (SEO / SNS)</h2>
                <div className="grid grid-cols-2 gap-4">
                  <Field label="카카오/SNS 공유 제목"><input value={exposureTitle} onChange={(e) => setExposureTitle(e.target.value)} placeholder="공유 시 표시될 제목" className={inputCls} /></Field>
                  <Field label="공유 이미지 URL"><input value={exposureImage} onChange={(e) => setExposureImage(e.target.value)} placeholder="https://..." className={inputCls} /></Field>
                </div>
                <Field label="페이지 설명"><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="검색 엔진 및 SNS 공유 시 표시될 설명" className={inputCls} /></Field>
                <Field label="헤더 스크립트 (픽셀 등)">
                  <textarea value={headerScript} onChange={(e) => setHeaderScript(e.target.value)} placeholder="<script>...</script>" rows={3}
                    className="w-full border border-gray-200 rounded-lg px-3 py-2 text-xs font-mono focus:outline-none focus:ring-2 focus:ring-blue-500 resize-y" />
                </Field>
              </section>

              {/* Payment */}
              <section className="space-y-4">
                <h2 className="text-sm font-semibold text-gray-700 border-b border-gray-100 pb-2">결제 설정</h2>
                <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
                  <input type="checkbox" checked={paymentEnabled} onChange={(e) => setPaymentEnabled(e.target.checked)} className="w-4 h-4 rounded border-gray-300" /> 결제 기능 사용
                </label>
                {paymentEnabled && (
                  <div className="grid grid-cols-2 gap-4 pl-6 border-l-2 border-blue-200">
                    <Field label="결제 유형">
                      <select value={paymentType} onChange={(e) => setPaymentType(e.target.value)} className={inputCls}>
                        <option value="onetime">일반 결제</option>
                        <option value="subscription">정기 결제</option>
                      </select>
                    </Field>
                    <Field label="상품명"><input value={productName} onChange={(e) => setProductName(e.target.value)} placeholder="상품명" className={inputCls} /></Field>
                    <Field label="금액 (원)"><input type="number" value={productPrice} onChange={(e) => setProductPrice(e.target.value)} placeholder="0" className={inputCls} /></Field>
                    {paymentType === 'subscription' && (<>
                      <Field label="결제일">
                        <select value={cycleDay} onChange={(e) => setCycleDay(e.target.value)} className={inputCls}>
                          {Array.from({ length: 31 }, (_, i) => <option key={i + 1} value={i + 1}>매월 {i + 1}일</option>)}
                        </select>
                      </Field>
                      <Field label="만료일"><input type="date" value={expireDate} onChange={(e) => setExpireDate(e.target.value)} className={inputCls} /></Field>
                    </>)}
                  </div>
                )}
              </section>

              {/* Email settings */}
              <section className="space-y-4">
                <h2 className="text-sm font-semibold text-gray-700 border-b border-gray-100 pb-2">신청 완료 이메일</h2>
                <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
                  <input type="checkbox" checked={regEmailEnabled} onChange={(e) => setRegEmailEnabled(e.target.checked)} className="w-4 h-4 rounded border-gray-300" /> 이메일 자동 발송
                </label>
                {regEmailEnabled && (
                  <div className="space-y-3 pl-6 border-l-2 border-blue-200">
                    <Field label="이메일 제목"><input value={regEmailSubject} onChange={(e) => setRegEmailSubject(e.target.value)} placeholder="예: [이름]님, 신청이 완료되었습니다" className={inputCls} /></Field>
                    <Field label="이메일 본문">
                      <textarea value={regEmailContent} onChange={(e) => setRegEmailContent(e.target.value)} placeholder="[고객명] 변수 사용 가능, HTML 태그 허용" rows={4}
                        className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-y" />
                    </Field>
                  </div>
                )}
              </section>
            </div>
          </div>

          {/* Right: iPhone preview */}
          <div className="w-[380px] shrink-0 bg-gray-100 flex flex-col items-center justify-start p-6 overflow-y-auto">
            <div className="text-xs text-gray-400 mb-3 font-medium">미리보기</div>
            <div className="w-[320px] bg-black rounded-[40px] p-3 shadow-2xl">
              <div className="flex justify-center mb-1"><div className="w-24 h-5 bg-black rounded-b-2xl" /></div>
              <div className="bg-white rounded-[28px] overflow-hidden h-[580px]">
                <iframe
                  srcDoc={`<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;font-family:-apple-system,sans-serif;font-size:14px;overflow-x:hidden;}img{max-width:100%;height:auto;}</style></head><body>${html}</body></html>`}
                  className="w-full h-full border-0" title="미리보기" sandbox="allow-scripts" />
              </div>
              <div className="flex justify-center mt-2"><div className="w-28 h-1 bg-gray-600 rounded-full" /></div>
            </div>
          </div>
        </div>
      )}

      {/* ── Tab 2: Registrations ── */}
      {tab === 'registrations' && (
        <div className="flex-1 overflow-y-auto p-6 bg-gray-50">
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-base font-semibold text-gray-800">
                등록자 목록
                <span className="ml-2 px-2 py-0.5 bg-blue-100 text-blue-700 text-xs rounded-full font-bold">{registrations.length}명</span>
              </h2>
            </div>
            {registrations.length === 0 ? (
              <div className="text-center py-16">
                <Users className="w-12 h-12 text-gray-300 mx-auto mb-3" />
                <p className="text-sm text-gray-500">아직 등록자가 없습니다.</p>
              </div>
            ) : (
              <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-gray-100 bg-gray-50">
                      {['이름', '연락처', '이메일', 'UTM', '상태', '등록일'].map((h) => (
                        <th key={h} className="text-left px-4 py-3 text-xs font-medium text-gray-500">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {registrations.map((reg) => (
                      <tr key={reg.id} className="border-b border-gray-50 hover:bg-gray-50 transition-colors">
                        <td className="px-4 py-3 font-medium text-gray-800">{reg.name}</td>
                        <td className="px-4 py-3 text-gray-600">
                          <span className="flex items-center gap-1"><Phone className="w-3 h-3 text-gray-400" />{maskPhone(reg.phone)}</span>
                        </td>
                        <td className="px-4 py-3 text-gray-600">
                          {reg.email ? <span className="flex items-center gap-1"><Mail className="w-3 h-3 text-gray-400" />{reg.email}</span> : <span className="text-gray-300">-</span>}
                        </td>
                        <td className="px-4 py-3">
                          {reg.utmSource ? (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-blue-50 text-blue-600 text-xs rounded-full font-medium"><Tag className="w-3 h-3" />{reg.utmSource}</span>
                          ) : <span className="text-gray-300">-</span>}
                        </td>
                        <td className="px-4 py-3">
                          {reg.funnelStarted
                            ? <span className="inline-flex items-center px-2 py-0.5 bg-purple-100 text-purple-700 text-xs rounded-full font-bold">퍼널진입</span>
                            : <span className="text-xs text-gray-400">대기</span>}
                        </td>
                        <td className="px-4 py-3 text-gray-500 text-xs">
                          <span className="flex items-center gap-1"><Calendar className="w-3 h-3 text-gray-400" />{fmtDate(reg.createdAt)}</span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      )}

      {/* ── Tab 3: Comments ── */}
      {tab === 'comments' && (
        <div className="flex-1 overflow-y-auto p-6 bg-gray-50">
          <div className="max-w-3xl mx-auto">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-base font-semibold text-gray-800">
                후기 관리
                <span className="ml-2 px-2 py-0.5 bg-amber-100 text-amber-700 text-xs rounded-full font-bold">{comments.length}개</span>
              </h2>
              <div className="relative">
                <button onClick={() => setGenDropdownOpen((v) => !v)} disabled={generating}
                  className="flex items-center gap-1.5 px-4 py-2 bg-purple-600 text-white rounded-lg text-sm font-medium hover:bg-purple-700 disabled:opacity-50">
                  {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                  AI 후기 자동 생성 <ChevronDown className="w-3 h-3" />
                </button>
                {genDropdownOpen && !generating && (<>
                  <div className="fixed inset-0 z-10" onClick={() => setGenDropdownOpen(false)} />
                  <div className="absolute right-0 mt-1 bg-white rounded-lg shadow-lg border border-gray-200 py-1 z-20 min-w-[120px]">
                    {[3, 5, 7, 10].map((n) => (
                      <button key={n} onClick={() => generateComments(n)}
                        className="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-purple-50 hover:text-purple-700">{n}개 생성</button>
                    ))}
                  </div>
                </>)}
              </div>
            </div>
            {commentMsg && (
              <div className={`mb-4 px-4 py-2 rounded-lg text-sm ${commentMsg.includes('실패') ? 'bg-red-50 text-red-600' : 'bg-green-50 text-green-600'}`}>{commentMsg}</div>
            )}
            {comments.length === 0 ? (
              <div className="text-center py-16">
                <MessageSquare className="w-12 h-12 text-gray-300 mx-auto mb-3" />
                <p className="text-sm text-gray-500">후기가 없습니다.</p>
                <p className="text-xs text-gray-400 mt-1">AI 후기 자동 생성 버튼으로 후기를 만들어보세요.</p>
              </div>
            ) : (
              <div className="space-y-3">
                {comments.map((c) => (
                  <div key={c.id} className="bg-white rounded-xl border border-gray-200 p-4 hover:border-gray-300 transition-colors">
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1.5">
                          <span className="text-sm font-semibold text-gray-800">{c.authorName}</span>
                          {c.isAutoGenerated && <span className="px-1.5 py-0.5 bg-purple-100 text-purple-600 text-[10px] rounded-full font-bold">AI생성</span>}
                          <span className="text-xs text-gray-400">{fmtDate(c.createdAt)}</span>
                        </div>
                        <p className="text-sm text-gray-600 leading-relaxed">{c.content}</p>
                      </div>
                      <button onClick={() => deleteComment(c.id)} className="shrink-0 p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg" title="삭제">
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}

      {/* ── Tab 4: Stats ── */}
      {tab === 'stats' && (
        <div className="flex-1 overflow-y-auto p-6 bg-gray-50">
          <div className="max-w-2xl mx-auto">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-base font-semibold text-gray-800">퍼널 전환 통계</h2>
              <button onClick={loadStats} disabled={statsLoading}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-white border border-gray-200 text-gray-600 rounded-lg text-xs font-medium hover:bg-gray-50 disabled:opacity-50">
                <RefreshCw className={`w-3.5 h-3.5 ${statsLoading ? 'animate-spin' : ''}`} /> 새로고침
              </button>
            </div>
            {statsLoading ? (
              <div className="space-y-4">{[...Array(3)].map((_, i) => <div key={i} className="h-20 bg-gray-200 animate-pulse rounded-xl" />)}</div>
            ) : stats ? (
              <div className="space-y-0">
                {/* Step 1: Views */}
                <div className="bg-gray-100 rounded-t-xl px-5 py-4 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-gray-200 flex items-center justify-center"><span className="text-xs font-bold text-gray-500">1</span></div>
                    <div><p className="text-sm font-semibold text-gray-700">방문</p><p className="text-[10px] text-gray-400">페이지 조회 수</p></div>
                  </div>
                  <span className="text-2xl font-bold text-gray-700 tabular-nums">{stats.viewCount.toLocaleString()}</span>
                </div>
                <div className="flex items-center justify-center py-2 bg-gray-50">
                  <div className="flex items-center gap-2 text-xs text-gray-400"><span>▼</span><span className="font-medium text-blue-600">전환율 {stats.visitToRegister}%</span></div>
                </div>
                {/* Step 2: Registered */}
                <div className="bg-blue-50 px-5 py-4 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center"><span className="text-xs font-bold text-blue-600">2</span></div>
                    <div><p className="text-sm font-semibold text-blue-700">신청</p><p className="text-[10px] text-blue-400">폼 제출 수</p></div>
                  </div>
                  <span className="text-2xl font-bold text-blue-700 tabular-nums">{stats.registered.toLocaleString()}</span>
                </div>
                <div className="flex items-center justify-center py-2 bg-gray-50">
                  <div className="flex items-center gap-2 text-xs text-gray-400"><span>▼</span><span className="font-medium text-amber-600">전환율 {stats.registerToFunnel}%</span></div>
                </div>
                {/* Step 3: Funnel Entered */}
                <div className="bg-amber-50 rounded-b-xl px-5 py-4 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-amber-100 flex items-center justify-center"><span className="text-xs font-bold text-amber-600">3</span></div>
                    <div><p className="text-sm font-semibold text-amber-700">퍼널진입</p><p className="text-[10px] text-amber-400">자동 퍼널 시작 수</p></div>
                  </div>
                  <span className="text-2xl font-bold text-amber-700 tabular-nums">{stats.funnelEntered.toLocaleString()}</span>
                </div>
                {/* Summary */}
                <div className="mt-6 p-4 bg-white rounded-xl border border-gray-200">
                  <p className="text-xs text-gray-500 mb-2 font-medium">전체 전환 요약</p>
                  <div className="grid grid-cols-3 gap-4 text-center">
                    <div><p className="text-xl font-bold text-gray-700 tabular-nums">{stats.viewCount.toLocaleString()}</p><p className="text-[10px] text-gray-400 mt-0.5">방문</p></div>
                    <div><p className="text-xl font-bold text-blue-600 tabular-nums">{stats.visitToRegister}%</p><p className="text-[10px] text-gray-400 mt-0.5">방문 → 신청</p></div>
                    <div><p className="text-xl font-bold text-amber-600 tabular-nums">{stats.registerToFunnel}%</p><p className="text-[10px] text-gray-400 mt-0.5">신청 → 퍼널</p></div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="text-center py-16">
                <BarChart2 className="w-12 h-12 text-gray-300 mx-auto mb-3" />
                <p className="text-sm text-gray-500">통계를 불러오지 못했습니다.</p>
                <button onClick={loadStats} className="mt-3 text-xs text-blue-600 hover:underline">다시 시도</button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
