import { NextResponse } from 'next/server'
import prisma from '@/lib/prisma'
import { getAuthContext, resolveOrgId } from '@/lib/rbac'
import type { PsychologyLens } from '@/types/funnel-wizard'
import { VARIABLES } from '@/types/funnel-wizard'

interface AutoCreateRequest {
  contactId: string
  psychologyLens: PsychologyLens
  selectedStrategy: string
  customMessages: Record<'0' | '1' | '2' | '3', string>
  schedule?: {
    startDate: string
    duration: 3 | 7 | 14
    hour: 8 | 12 | 18
  }
}

// POST /api/funnels/auto-create
// 판매원이 마법사로 작성한 자동메시지 저장
export async function POST(req: Request) {
  try {
    const ctx = await getAuthContext()
    if (!ctx.userId) {
      return NextResponse.json({ ok: false, error: '인증 필요' }, { status: 401 })
    }

    const orgId = resolveOrgId(ctx)
    if (!orgId) {
      return NextResponse.json({ ok: false, error: '조직 정보 필요' }, { status: 403 })
    }

    const body: AutoCreateRequest = await req.json()

    // 입력 검증
    if (!body.contactId || !body.psychologyLens || !body.customMessages) {
      return NextResponse.json(
        { ok: false, error: '필수 필드 누락' },
        { status: 400 }
      )
    }

    // Contact 존재 확인
    const contact = await prisma.contact.findFirst({
      where: { id: body.contactId, organizationId: orgId },
    })

    if (!contact) {
      return NextResponse.json(
        { ok: false, error: '고객을 찾을 수 없습니다' },
        { status: 404 }
      )
    }

    // 스케줄 기본값
    const schedule = body.schedule || {
      startDate: new Date().toISOString().split('T')[0],
      duration: 3,
      hour: 12,
    }

    // Funnel + ScheduledSms 트랜잭션 생성
    const funnel = await prisma.$transaction(async (tx) => {
      // 1. Funnel 생성
      const newFunnel = await tx.funnel.create({
        data: {
          organizationId: orgId,
          name: `[${body.psychologyLens}] ${contact.name} 자동메시지`,
          description: body.selectedStrategy,
          funnelType: 'SMS_WIZARD',
          visibility: 'PERSONAL',
          autoGenerated: true,
          psychologyLens: body.psychologyLens,
          templateVersion: 1,
          createdByUserId: ctx.userId,
        },
      })

      // 2. Day 0-3 ScheduledSms 생성
      const baseDate = new Date(schedule.startDate)
      baseDate.setHours(schedule.hour, 0, 0, 0)

      for (let day = 0; day < Math.min(4, schedule.duration); day++) {
        const scheduledAt = new Date(baseDate)
        scheduledAt.setDate(scheduledAt.getDate() + day)

        const msgKey = String(day) as '0' | '1' | '2' | '3'
        await tx.scheduledSms.create({
          data: {
            organizationId: orgId,
            contactId: body.contactId,
            message: body.customMessages[msgKey] || '',
            scheduledAt,
            status: 'PENDING',
            sentCount: 0,
            failedCount: 0,
            createdByUserId: ctx.userId,
          },
        })
      }

      return newFunnel
    })

    return NextResponse.json({
      ok: true,
      data: {
        funnelId: funnel.id,
        contactId: body.contactId,
        status: 'ACTIVE',
        psychologyLens: body.psychologyLens,
        scheduledMessages: Math.min(4, schedule.duration),
        nextMessageAt: new Date(schedule.startDate).toISOString(),
      },
    })
  } catch (error) {
    console.error('❌ POST /api/funnels/auto-create 에러:', error)
    return NextResponse.json(
      { ok: false, error: '서버 에러' },
      { status: 500 }
    )
  }
}
