// 판매원 자동메시지 생성기 타입 정의

export type PsychologyLens = 'L0' | 'L1' | 'L2' | 'L3' | 'L4' | 'L5' | 'L6' | 'L7' | 'L8' | 'L9' | 'L10'

export const LENS_DETAILS: Record<PsychologyLens, { name: string; description: string; strategies: string[] }> = {
  L0: {
    name: '부재중 고객',
    description: '3-6개월 이상 연락 없던 고객들',
    strategies: ['따뜻한 재진입', '특별 감사 오퍼', '새 상품 소개'],
  },
  L1: {
    name: '가격 이의',
    description: '가격이 비싸다고 느끼는 고객',
    strategies: ['가치 재정의', '쉬운 결제 방식', '할부 제안'],
  },
  L2: {
    name: '준비 불안',
    description: '준비가 복잡하다고 느끼는 고객',
    strategies: ['준비 과정 단순화', '자세한 가이드', '준비 대행 안내'],
  },
  L3: {
    name: '경쟁사 비교',
    description: '다른 상품과 비교하는 고객',
    strategies: ['비교표 제시', '차별성 강조', '고객 후기'],
  },
  L4: {
    name: '자유도 우려',
    description: '구속감이나 자유도를 걱정하는 고객',
    strategies: ['유연성 강조', '자유로운 취소 정책', '맞춤형 서비스'],
  },
  L5: {
    name: '능력 불신',
    description: '이 상품이 정말 효과 있을까 의심하는 고객',
    strategies: ['전문성 증명', '성공 사례', '과학적 근거'],
  },
  L6: {
    name: '타이밍 중요',
    description: '지금 바로 결정해야 할 것 같은 고객',
    strategies: ['긴박감 강조', '기간 한정 오퍼', '빨리 결정할 이유'],
  },
  L7: {
    name: '가족 설득',
    description: '가족과 함께 결정해야 하는 고객',
    strategies: ['가족 공개 특가', '함께 즐기는 이야기', '가족 할인'],
  },
  L8: {
    name: '습관 형성',
    description: '반복 구매 가능성이 높은 고객',
    strategies: ['구독 플랜', '멤버십 혜택', '정기 할인'],
  },
  L9: {
    name: '건강 신뢰',
    description: '건강이나 안전을 중요시하는 고객',
    strategies: ['안전성 증명', '건강 효과', '신뢰 인증'],
  },
  L10: {
    name: '즉시 구매',
    description: '이미 거의 결정한 상태의 고객',
    strategies: ['최후 한 푸시', '즉시 구매 혜택', '오늘의 특가'],
  },
}

export type PasonaStage = 'PROBLEM' | 'AGITATE' | 'SOLUTION' | 'OFFER' | 'NARROW' | 'ACTION'

export interface DayMessage {
  day: 0 | 1 | 2 | 3
  pasona: PasonaStage
  content: string
  variables: string[]
}

export interface FunnelLensTemplate {
  lens: PsychologyLens
  name: string
  description: string
  messages: DayMessage[]
}

export interface FunnelWizardState {
  step: 1 | 2 | 3 | 4 | 5
  selectedLens?: PsychologyLens
  selectedStrategy?: string
  customMessages?: Record<0 | 1 | 2 | 3, string>
  schedule?: {
    startDate: string
    duration: 3 | 7 | 14
    hour: 8 | 12 | 18
  }
}

export interface FunnelTemplate {
  id: string
  organizationId: string
  name: string
  psychologyLens: PsychologyLens
  visibility: 'PERSONAL' | 'TEAM' | 'PUBLIC'
  autoGenerated: boolean
  templateVersion: number
  dayMessages: DayMessage[]
}

// 동적 변수 정의
export const VARIABLES = {
  고객명: '{{고객명}}',
  전화번호: '{{전화번호}}',
  담당자명: '{{담당자명}}',
  상품명: '{{상품명}}',
  출발일: '{{출발일}}',
} as const

export type VariableKey = keyof typeof VARIABLES
