/**
 * Funnel & Psychology Lens Type Definitions
 *
 * 렌즈별 템플릿 관련 TypeScript 타입 정의
 * CLAUDE.md Template 1-12 기반 자동완성 지원
 *
 * 버전: 1.0 (2026-06-24)
 */

// ============================================================================
// Psychology Lens Enum (심리학 렌즈 L0-L10)
// ============================================================================

/**
 * Grant Cardone 10 렌즈 + L0 (부재중 고객)
 *
 * - L0: 부재중 고객 (비활성, 구매 미진행)
 * - L1: 가격 이의 (비용 민감)
 * - L2: 준비 복잡도 (시간/절차 불안)
 * - L3: 경쟁사 비교 (차별성 미흡)
 * - L4: [Template 4 이상에서 확장 가능]
 * - L5: 적합성/자기투영 (필요성 불명확)
 * - L6: 타이밍/손실회피 (긴박감 + 후회 우려)
 * - L7: 동반자/가족 설득 (의사결정권 분산)
 * - L8: 재구매/습관적 성장 (장기 고객화)
 * - L9: 의료/안전 신뢰 (권위성 + 의료정보)
 * - L10: 즉시 구매 클로징 (결정직전, FOMO)
 */
export enum PsychologyLens {
  L0 = 'L0_INACTIVE_CUSTOMERS',           // 부재중 고객
  L1 = 'L1_PRICE_OBJECTION',              // 가격 이의
  L2 = 'L2_PREPARATION_COMPLEXITY',       // 준비 복잡도
  L3 = 'L3_COMPETITOR_COMPARISON',        // 경쟁사 비교
  L5 = 'L5_SUITABILITY_SELF_PROJECTION',  // 적합성/자기투영
  L6 = 'L6_TIMING_LOSS_AVERSION',         // 타이밍/손실회피
  L7 = 'L7_COMPANION_FAMILY_PERSUASION',  // 동반자/가족 설득
  L8 = 'L8_REPURCHASE_HABITUAL_GROWTH',   // 재구매/습관 성장
  L9 = 'L9_HEALTH_SAFETY_MEDICAL_TRUST',  // 의료/안전 신뢰
  L10 = 'L10_IMMEDIATE_PURCHASE_CLOSING', // 즉시 구매 클로징
}

// ============================================================================
// Variable Interface (동적 변수)
// ============================================================================

/**
 * SMS/Email 메시지에서 사용할 동적 변수
 *
 * 예시:
 * - key: "고객명", placeholder: "{{고객명}}"
 * - key: "상품명", placeholder: "{{상품명}}"
 * - key: "할인율", placeholder: "{{할인율}}%"
 */
export interface Variable {
  key: string;              // 변수 이름 (예: "고객명", "상품명", "할인율")
  placeholder: string;      // 메시지에 삽입될 형식 (예: "{{고객명}}", "{{상품명}}")
  required?: boolean;       // 필수 변수 여부 (기본값: false)
  sampleValue?: string;     // 미리보기용 샘플 값
}

// ============================================================================
// DayMessage Interface (Day별 PASONA 메시지)
// ============================================================================

/**
 * PASONA 프레임워크 기반 Day별 메시지 템플릿
 *
 * PASONA 단계:
 * - P (PROBLEM): 고객 문제 상황 파악
 * - S (SOLUTION): 해결책 제시
 * - O (OFFER): 구체적 오퍼/제안
 * - N (NARROW): 선택지 좁히기 (2-3개 옵션)
 * - A (ACTION): 행동 촉구 (클릭/신청/구매)
 *
 * Day 0-3 흐름:
 * - Day 0: P + A (초기 문제 인식 + 클릭 유도)
 * - Day 1: S (해결책 제시 + 신뢰 구축)
 * - Day 2: O + N (구체 오퍼 + 선택지 제시)
 * - Day 3: A (최종 클로징 + 긴박감)
 */
export interface DayMessage {
  day: 0 | 1 | 2 | 3;                           // 발송 요일 (Day 0 ~ 3)
  pasona: 'PROBLEM' | 'SOLUTION' | 'OFFER' | 'ACTION' | 'NARROW';  // PASONA 단계
  content: string;                               // 메시지 본문 (변수 포함 가능)
  variables?: Variable[];                        // 이 메시지에 사용되는 동적 변수 목록
  characterCount?: number;                       // 문자 수 (SMS 90자 또는 이메일 길이)
  isAutoGenerated?: boolean;                     // AI 자동 생성 여부
}

// ============================================================================
// Strategy Interface (대응 전략)
// ============================================================================

/**
 * 고객 세그먼트/렌즈별 응답 전략
 *
 * 예시:
 * - L1(가격): "할부제안" 전략 → 월 60만원 × 5개월
 * - L6(손실): "긴박감" 전략 → "오늘만 20% 할인"
 * - L10(클로징): "즉시구매" 전략 → "1시간 내 결정시 추가 특전"
 */
export interface Strategy {
  id: string;                      // 전략 ID (예: "strat-installment-l1")
  name: string;                    // 전략명 (예: "할부제안 전략")
  description: string;             // 상세 설명
  messageTemplate: string;         // 메시지 템플릿 (Day별로 분리 가능)
  psychologyLens: PsychologyLens;  // 적용 렌즈
  targetSegment?: string;          // 대상 세그먼트 (예: "가격민감층")
  expectedConversionRate?: number; // 예상 전환율 (%)
}

// ============================================================================
// FunnelTemplate Interface (퍼널 템플릿)
// ============================================================================

/**
 * 완성된 퍼널 템플릿 (렌즈별, Day별, 메시지 포함)
 *
 * 용도:
 * - 관리자가 미리 제작한 템플릿 목록
 * - 사용자가 선택해서 클론 → 커스터마이징
 * - 성과 측정 기준으로 활용
 */
export interface FunnelTemplate {
  id: string;                              // 템플릿 ID
  name?: string;                           // 템플릿명 (예: "L6 긴박감 3일 퍼널")
  psychologyLens: PsychologyLens;          // 적용 렌즈
  strategies: Strategy[];                  // 포함된 전략 목록
  dayMessages: DayMessage[];               // Day 0-3 메시지 템플릿
  autoGenerated: boolean;                  // AI 자동 생성 여부
  description?: string;                    // 템플릿 설명
  expectedConversionRate?: number;         // 예상 전환율 (%)
  expectedLTV?: number;                    // 예상 생명주기 가치
  tags?: string[];                         // 분류 태그 (예: ["할부", "긴박감", "3일"])
  createdAt?: string;                      // 생성일
  updatedAt?: string;                      // 수정일
}

// ============================================================================
// FunnelWizardStep Interface (퍼널 마법사 상태)
// ============================================================================

/**
 * 5단계 퍼널 설정 마법사 상태 관리
 *
 * 5단계 흐름:
 * 1. 렌즈 선택 (어떤 심리학 렌즈?)
 * 2. 전략 선택 (어떤 응답 전략?)
 * 3. 메시지 커스터마이징 (Day 0-3 메시지 편집)
 * 4. 스케줄 설정 (시작일, 발송 시간)
 * 5. 확인 & 생성 (검토 후 최종 생성)
 */
export interface FunnelWizardStep {
  currentStep: 1 | 2 | 3 | 4 | 5;                    // 현재 단계
  selectedLens?: PsychologyLens;                     // 선택된 렌즈
  selectedStrategy?: string;                         // 선택된 전략 ID
  selectedStrategyName?: string;                     // 선택된 전략명 (UI 표시용)
  customMessages?: {                                 // Day별 커스텀 메시지
    day0: string;
    day1: string;
    day2: string;
    day3: string;
  };
  messageVariables?: Record<string, string>;         // 변수 입력값 (예: {"고객명": "김철수", "상품명": "발리 프리미엄 투어"})
  schedule?: {                                       // 발송 스케줄
    startDate: string;                               // 시작일 (YYYY-MM-DD)
    duration: 3 | 7 | 14;                            // 기간 (3일/1주/2주)
    hour: 8 | 12 | 18;                               // 발송 시간대 (08:00, 12:00, 18:00)
    timezone?: string;                               // 타임존 (기본값: Asia/Seoul)
  };
  isPreviewMode?: boolean;                           // 미리보기 모드 여부
  validationErrors?: string[];                       // 유효성 검사 오류 목록
}

// ============================================================================
// Funnel Interface (생성된 퍼널 인스턴스)
// ============================================================================

/**
 * 실제 사용 중인 퍼널 인스턴스
 * (DB에 저장되고, 매 Day마다 자동 발송되는 실제 퍼널)
 */
export interface Funnel {
  id: string;                              // 퍼널 ID
  organizationId: string;                  // 조직 ID (멀티테넌트)
  createdBy: string;                       // 생성자 (사용자 ID)
  name: string;                            // 퍼널명
  psychologyLens: PsychologyLens;          // 적용 렌즈
  strategy: Strategy;                      // 사용된 전략
  messages: DayMessage[];                  // Day 0-3 메시지 (템플릿 기반)
  schedule: {
    startDate: string;                     // 시작일
    duration: 3 | 7 | 14;                  // 기간
    hour: 8 | 12 | 18;                     // 발송 시간
    timezone: string;                      // 타임존
  };
  status: 'DRAFT' | 'ACTIVE' | 'PAUSED' | 'COMPLETED' | 'FAILED';
  statistics?: {
    totalContacts: number;                 // 대상 고객 수
    sentCount: number;                     // 발송 완료
    failedCount: number;                   // 발송 실패
    openCount: number;                     // 개봉/확인
    clickCount: number;                    // 클릭
    conversionCount: number;               // 전환 (구매/신청)
    conversionRate?: number;               // 전환율 (%)
  };
  createdAt: string;
  updatedAt: string;
}

// ============================================================================
// PreviewMessage Interface (미리보기 메시지)
// ============================================================================

/**
 * Day별 메시지 미리보기 (변수 치환 후)
 *
 * 용도:
 * - 마법사 Step 3에서 실시간 미리보기
 * - 변수 입력 후 즉시 반영
 */
export interface PreviewMessage {
  day: 0 | 1 | 2 | 3;
  originalContent: string;                 // 원본 (변수 포함)
  previewContent: string;                  // 미리보기 (변수 치환됨)
  characterCount: number;
  estimatedSendTime?: string;              // 예상 발송 시간
}

// ============================================================================
// FunnelAnalytics Interface (성과 분석)
// ============================================================================

/**
 * 퍼널별 성과 분석 데이터
 *
 * 용도:
 * - 대시보드 KPI 표시
 * - A/B 테스트 비교
 * - ROI 계산
 */
export interface FunnelAnalytics {
  funnelId: string;
  psychologyLens: PsychologyLens;
  period: {
    startDate: string;
    endDate: string;
  };
  metrics: {
    totalSent: number;
    totalFailed: number;
    totalOpened: number;
    totalClicked: number;
    totalConverted: number;

    // 비율
    openRate: number;                      // 개봉율 (%)
    clickRate: number;                     // 클릭율 (%)
    conversionRate: number;                // 전환율 (%)

    // 금액
    totalRevenue?: number;                 // 총 매출
    costPerAcquisition?: number;           // 고객 획득 비용
    lifetimeValue?: number;                // 고객 생명주기 가치
  };
  dayBreakdown?: {                         // Day별 분석
    [key in 0 | 1 | 2 | 3]?: {
      sent: number;
      opened: number;
      clicked: number;
      converted: number;
    };
  };
  topPerformingMessage?: string;           // 가장 성과 좋은 메시지
  recommendation?: string;                 // AI 추천사항
}
