-- Migration: Add Funnel Partner Wizard fields (createdByUserId, visibility, autoGenerated, psychologyLens, templateVersion)
-- Date: 2026-06-24
-- Purpose: Enable Partner Funnel Wizard Phase 1 features for base Funnel model
-- Note: FunnelSms and FunnelEmail models already have these fields; this adds them to the legacy Funnel table

-- ============================================================
-- Step 1: Add new columns to Funnel table
-- ============================================================

ALTER TABLE "Funnel" ADD COLUMN IF NOT EXISTS "createdByUserId" TEXT;
ALTER TABLE "Funnel" ADD COLUMN IF NOT EXISTS "visibility" VARCHAR(10) NOT NULL DEFAULT 'PUBLIC';
ALTER TABLE "Funnel" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Funnel" ADD COLUMN IF NOT EXISTS "psychologyLens" VARCHAR(3);
ALTER TABLE "Funnel" ADD COLUMN IF NOT EXISTS "templateVersion" INTEGER NOT NULL DEFAULT 1;

-- ============================================================
-- Step 2: Add indexes for query optimization
-- ============================================================

-- Index for creator-based queries (find funnels by creator)
CREATE INDEX IF NOT EXISTS "idx_funnel_org_creator_time"
ON "Funnel"("organizationId", "createdByUserId", "createdAt" DESC);

-- Index for lens-based segmentation (psychology lens filtering)
CREATE INDEX IF NOT EXISTS "idx_funnel_org_lens_visibility"
ON "Funnel"("organizationId", "psychologyLens", "visibility");

-- Index for template queries (find template funnels)
CREATE INDEX IF NOT EXISTS "idx_funnel_org_template_version"
ON "Funnel"("organizationId", "templateVersion");

-- Index for visibility-based access control
CREATE INDEX IF NOT EXISTS "idx_funnel_visibility_org"
ON "Funnel"("visibility", "organizationId");

-- ============================================================
-- Step 3: Data migration (set default values for existing records)
-- ============================================================

-- Set createdByUserId to NULL (nullable, will be populated by application)
-- visibility already has DEFAULT 'PUBLIC' from column creation
-- autoGenerated defaults to false (not auto-generated legacy records)
-- psychologyLens defaults to NULL (will be classified by wizard)
-- templateVersion defaults to 1 (first version)

-- No UPDATE statement needed since all columns have defaults from column creation

-- ============================================================
-- Step 4: Foreign key consideration (createdByUserId)
-- ============================================================
-- Note: createdByUserId is NOT a foreign key to User.id because:
-- 1. Partner funnel creators may be from different organizations
-- 2. Cross-org collaboration use cases need flexibility
-- 3. Deleted users should not cascade-delete funnels
-- 4. This is an audit/tracking field, not a data relationship
--
-- If in future you need FK constraint, add separately:
-- ALTER TABLE "Funnel" ADD CONSTRAINT "Funnel_createdByUserId_fkey"
--   FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL;

-- ============================================================
-- Step 5: Verification
-- ============================================================
-- SELECT COUNT(*) FROM "Funnel"; -- should return row count
-- SELECT DISTINCT visibility FROM "Funnel"; -- should show 'PUBLIC'
-- SELECT COUNT(*) FROM "Funnel" WHERE "autoGenerated" = true; -- should be 0
