export const dynamic = 'force-dynamic';

// app/api/admin/landing-pages/[id]/comments/route.ts
// 관리자용 랜딩페이지 댓글 조회 API

import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getSessionUser } from '@/lib/auth';

/**
 * GET: 랜딩페이지 댓글 목록 조회 (관리자/대리점장)
 */
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> | { id: string } }
) {
  try {
    const user = await getSessionUser();
    if (!user) {
      return NextResponse.json(
        { ok: false, error: '인증이 필요합니다.' },
        { status: 401 }
      );
    }

    const resolvedParams = await Promise.resolve(params);
    const landingPageId = parseInt(resolvedParams.id);

    if (isNaN(landingPageId)) {
      return NextResponse.json(
        { ok: false, error: '잘못된 랜딩페이지 ID입니다.' },
        { status: 400 }
      );
    }

    // 랜딩페이지 조회 및 권한 확인
    const landingPage = await prisma.landingPage.findFirst({
      where: {
        id: landingPageId,
        OR: [
          { adminId: user.id }, // 관리자가 생성한 페이지
          { adminId: { in: await prisma.user.findMany({ where: { role: 'admin' }, select: { id: true } }).then(users => users.map(u => u.id)) } }, // 관리자 페이지
        ],
      },
    });

    if (!landingPage) {
      // 대리점장인지 확인
      if (user.role === 'partner') {
        const profile = await prisma.affiliateProfile.findUnique({
          where: { userId: user.id },
          select: { type: true },
        });
        
        if (profile?.type === 'BRANCH_MANAGER') {
          // 대리점장이 생성한 페이지인지 확인
          const partnerPage = await prisma.landingPage.findFirst({
            where: {
              id: landingPageId,
              adminId: user.id,
            },
          });

          if (!partnerPage) {
            return NextResponse.json(
              { ok: false, error: '권한이 없습니다.' },
              { status: 403 }
            );
          }
        } else {
          return NextResponse.json(
            { ok: false, error: '권한이 없습니다.' },
            { status: 403 }
          );
        }
      } else {
        return NextResponse.json(
          { ok: false, error: '권한이 없습니다.' },
          { status: 403 }
        );
      }
    }

    // 댓글 목록 조회
    const comments = await prisma.landingPageComment.findMany({
      where: {
        landingPageId: landingPageId,
      },
      orderBy: {
        createdAt: 'desc',
      },
      take: 100,
    });

    return NextResponse.json({
      ok: true,
      comments: comments.map((comment) => ({
        id: comment.id,
        authorName: comment.authorName,
        content: comment.content,
        createdAt: comment.createdAt.toISOString(),
        isAutoGenerated: comment.isAutoGenerated,
      })),
    });
  } catch (error: any) {
    console.error('[Admin Landing Page Comments] Error:', error);
    return NextResponse.json(
      {
        ok: false,
        error: error.message || '댓글 조회 중 오류가 발생했습니다.',
      },
      { status: 500 }
    );
  }
}
