import { NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import prisma from '@/lib/prisma';
import { getAuthContext, requireOrgId } from '@/lib/rbac';
import { logger } from '@/lib/logger';

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

type Params = { params: Promise<{ id: string }> };

/**
 * POST /api/b2b-landing/[id]/comments/generate
 * B2B 교육 프로그램 랜딩페이지용 AI 생성 후기
 *
 * Request: { count: number } — 생성할 댓글 수 (1~10)
 * Response: { ok: true, comments: [...] }
 */
export async function POST(req: Request, { params }: Params) {
  try {
    const ctx = await getAuthContext();
    const orgId = requireOrgId(ctx);
    const { id } = await params;

    // B2B 랜딩페이지 조회 및 소유권 확인
    const page = await prisma.b2BLandingPage.findFirst({
      where: { id, organizationId: orgId },
      select: { id: true, title: true, htmlContent: true },
    });
    if (!page) {
      return NextResponse.json({ ok: false }, { status: 404 });
    }

    // 요청 바디 파싱
    const body = await req.json();
    const count = Math.min(10, Math.max(1, (parseInt(body.count ?? '5') || 5)));

    // HTML → 텍스트 추출 (태그 제거, 공백 정규화)
    const textContent = (page.htmlContent ?? '')
      .replace(/<[^>]*>/g, ' ')
      .replace(/\s+/g, ' ')
      .trim()
      .slice(0, 800);

    // B2B 교육 프로그램 수료자 관점 프롬프트
    const prompt = `당신은 B2B 교육 프로그램 수료자입니다.
마비즈의 B2B 파트너 교육 프로그램에 대해 실제 사업가/담당자 후기처럼 보이는 댓글 ${count}개를 JSON 배열로 생성하세요.

콘텐츠 맥락:
"""
${textContent}
"""

규칙:
- 각 댓글은 {"authorName": "이름", "content": "내용"} 형식
- authorName: 실제 한국 이름 (성씨 + 이름 2~3글자)
- content: 50~120자, 자연스럽고 구체적인 후기
- 교육 효과, 실무 활용, 추천 포함
- 사업가/담당자 입장 (예: "매출이 30% 증가했어요", "실무에 바로 적용 가능하네요")
- 마케팅 문구 같지 않게, 실제 전문가 느낌
- JSON 배열만 반환`;

    // Claude API 호출
    const message = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }],
    });

    // API 응답에서 텍스트 추출
    const raw = (message.content[0] as { type: string; text: string }).text.trim();

    // JSON 파싱 (배열 추출)
    const jsonMatch = raw.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      logger.error('[B2B generate comments] JSON 파싱 실패', {
        raw: raw.slice(0, 200),
      });
      return NextResponse.json(
        { ok: false, message: 'AI 응답 파싱 실패' },
        { status: 500 }
      );
    }

    const generated = JSON.parse(jsonMatch[0]) as {
      authorName: string;
      content: string;
    }[];

    // 트랜잭션으로 여러 댓글 동시 생성
    const created = await prisma.$transaction(
      generated.map((c) =>
        prisma.b2BLandingComment.create({
          data: {
            landingPageId: page.id,
            authorName: c.authorName,
            content: c.content,
            isAutoGenerated: true,
          },
          select: {
            id: true,
            authorName: true,
            content: true,
            createdAt: true,
          },
        })
      )
    );

    logger.log('[POST /api/b2b-landing/[id]/comments/generate]', {
      landingPageId: id,
      count: created.length,
      orgId,
    });

    return NextResponse.json({ ok: true, comments: created });
  } catch (err) {
    logger.error('[POST /api/b2b-landing/[id]/comments/generate]', { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}
