import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { logger } from "@/lib/logger";

type Params = { params: Promise<{ slug: string }> };

// GET /api/public/landing/[slug]/comments — 방문자용 댓글 조회 (인증 불필요)
export async function GET(_req: Request, { params }: Params) {
  try {
    const { slug } = await params;

    const page = await prisma.crmLandingPage.findFirst({
      where: { slug, isActive: true, isPublic: true },
      select: { id: true, commentEnabled: true },
    });
    if (!page || !page.commentEnabled) {
      return NextResponse.json({ ok: true, comments: [] });
    }

    const comments = await prisma.crmLandingComment.findMany({
      where:   { landingPageId: page.id },
      orderBy: { createdAt: "desc" },
      take:    50,
      select:  { id: true, authorName: true, content: true, isAutoGenerated: true, createdAt: true },
    });

    return NextResponse.json({ ok: true, comments });
  } catch (err) {
    logger.error("[GET /api/public/landing/[slug]/comments]", { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}

// POST /api/public/landing/[slug]/comments — 방문자 댓글 작성 (인증 불필요)
export async function POST(req: Request, { params }: Params) {
  try {
    const { slug } = await params;

    const page = await prisma.crmLandingPage.findFirst({
      where: { slug, isActive: true, isPublic: true, commentEnabled: true },
      select: { id: true },
    });
    if (!page) {
      return NextResponse.json({ ok: false, message: "댓글이 비활성화된 페이지입니다." }, { status: 404 });
    }

    const body = await req.json();
    const { authorName, content } = body as {
      authorName?: string; content?: string;
    };

    if (!authorName?.trim() || !content?.trim()) {
      return NextResponse.json({ ok: false, message: "이름과 내용을 입력하세요." }, { status: 400 });
    }
    if (content.trim().length > 500) {
      return NextResponse.json({ ok: false, message: "댓글은 500자 이내로 작성하세요." }, { status: 400 });
    }

    const comment = await prisma.crmLandingComment.create({
      data: {
        landingPageId:   page.id,
        authorName:      authorName.trim(),
        content:         content.trim(),
        isAutoGenerated: false,
      },
      select: { id: true, authorName: true, content: true, createdAt: true },
    });

    logger.log("[POST /api/public/landing/[slug]/comments]", { landingPageId: page.id });

    return NextResponse.json({ ok: true, comment });
  } catch (err) {
    logger.error("[POST /api/public/landing/[slug]/comments]", { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}
