import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { logger } from "@/lib/logger";
import { checkOrigin } from "@/lib/origin-guard";

type Params = { params: Promise<{ slug: string }> };

// GET /api/public/landing/[slug]/comments — 방문자용 댓글 조회 (인증 불필요)
export async function GET(_req: Request, { params }: Params) {
  try {
    const { slug } = await params;

    // 공개 URL은 shortlink 또는 slug 어느 쪽으로도 진입 가능(page.tsx와 동일 규칙).
    // shortlink는 전역 유일, slug는 (slug,org) 조합만 유일 → OR+findFirst는 비결정적(셰도잉 가능).
    // shortlink(전역유일) 우선 정확 매치 → 없으면 slug 폴백 = 항상 같은 페이지로 해석.
    let page = await prisma.crmLandingPage.findFirst({
      where: { shortlink: slug, isActive: true, isPublic: true },
      select: { id: true, commentEnabled: true },
    });
    if (!page) {
      page = await prisma.crmLandingPage.findFirst({
        where: { slug, isActive: true, isPublic: true },
        select: { id: true, commentEnabled: true },
      });
    }
    if (!page || !page.commentEnabled) {
      return NextResponse.json({ ok: true, comments: [] });
    }

    // 커뮤니티 Q&A(티키타카): 최상위 질문(parentId=null)만 페이지네이션 + 각 질문의 답글 중첩.
    const url = new URL(_req.url);
    const cursor = url.searchParams.get('cursor');
    const take = Math.min(Number(url.searchParams.get('take')) || 10, 50);

    const replySelect = {
      where:   { status: 'visible' },
      orderBy: { createdAt: 'asc' as const }, // 답글은 대화 흐름대로 오래된 순
      select:  { id: true, authorName: true, content: true, createdAt: true, authorRole: true, likeCount: true },
    };

    const questions = await prisma.crmLandingComment.findMany({
      where:   { landingPageId: page.id, parentId: null, status: 'visible' },
      orderBy: { createdAt: "desc" },
      take:    take + 1, // 다음 페이지 존재 여부 확인용
      ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}),
      select:  {
        id: true, authorName: true, content: true, createdAt: true,
        authorRole: true, likeCount: true,
        replies: replySelect,
      },
    });

    const hasMore = questions.length > take;
    const result = hasMore ? questions.slice(0, take) : questions;
    const nextCursor = hasMore ? result[result.length - 1]?.id : null;

    return NextResponse.json({ ok: true, comments: result, nextCursor });
  } catch (err) {
    logger.error("[GET /api/public/landing/[slug]/comments]", { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}

// POST /api/public/landing/[slug]/comments — 방문자 댓글 작성 (인증 불필요)
export async function POST(req: Request, { params }: Params) {
  try {
    if (!checkOrigin(req, 'LandingComment')) {
      return NextResponse.json({ ok: false, message: '허용되지 않은 요청입니다.' }, { status: 403 });
    }

    const { slug } = await params;

    // GET과 동일: shortlink(전역유일) 우선 → slug 폴백. 비결정성·셰도잉 제거.
    let page = await prisma.crmLandingPage.findFirst({
      where: { shortlink: slug, isActive: true, isPublic: true, commentEnabled: true },
      select: { id: true },
    });
    if (!page) {
      page = await prisma.crmLandingPage.findFirst({
        where: { slug, isActive: true, isPublic: true, commentEnabled: true },
        select: { id: true },
      });
    }
    if (!page) {
      return NextResponse.json({ ok: false, message: "댓글이 비활성화된 페이지입니다." }, { status: 404 });
    }

    const body = await req.json();
    const { authorName, content, parentId } = body as {
      authorName?: string; content?: string; parentId?: string;
    };

    if (!authorName?.trim() || !content?.trim()) {
      return NextResponse.json({ ok: false, message: "이름과 내용을 입력하세요." }, { status: 400 });
    }
    if (content.trim().length > 500) {
      return NextResponse.json({ ok: false, message: "500자 이내로 작성하세요." }, { status: 400 });
    }

    // 답글이면 부모 검증(같은 페이지 소속) + 1단계 깊이 제한(답글의 답글 금지 → 최상위 질문에 붙임)
    let effectiveParentId: string | null = null;
    if (parentId) {
      const parent = await prisma.crmLandingComment.findFirst({
        where:  { id: parentId, landingPageId: page.id, status: 'visible' },
        select: { id: true, parentId: true },
      });
      if (!parent) {
        return NextResponse.json({ ok: false, message: "원글을 찾을 수 없습니다." }, { status: 400 });
      }
      effectiveParentId = parent.parentId ?? parent.id; // 답글에 답글 달면 그 답글의 최상위 질문으로 귀속
    }

    const comment = await prisma.crmLandingComment.create({
      data: {
        landingPageId:   page.id,
        authorName:      authorName.trim(),
        content:         content.trim(),
        isAutoGenerated: false,
        parentId:        effectiveParentId,
      },
      select: { id: true, authorName: true, content: true, createdAt: true, authorRole: true, likeCount: true, parentId: true },
    });

    logger.log("[POST /api/public/landing/[slug]/comments]", { landingPageId: page.id });

    return NextResponse.json({ ok: true, comment });
  } catch (err) {
    logger.error("[POST /api/public/landing/[slug]/comments]", { err });
    return NextResponse.json({ ok: false }, { status: 500 });
  }
}
