// app/api/admin/mall/products/[productCode]/generate-detail-images/route.ts
// 상품 상세페이지 이미지 자동 생성 API
// 기존 DB 데이터를 읽어 Puppeteer로 5개 섹션 이미지 생성

import { NextRequest, NextResponse } from 'next/server';
import path from 'path';
import prisma from '@/lib/prisma';
import { getSession } from '@/lib/session';
import { isMallAdmin } from '@/lib/mall/mall-admin-permissions';
import { generateDetailImages, DetailImageData } from '@/lib/mall/detail-image-generator';
import { logger } from '@/lib/logger';
import { validateCsrfAndRespond } from '@/lib/api-utils';

export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ productCode: string }> },
) {
  const { productCode } = await params;

  try {
    // productCode 경로 순회(path traversal) 방지 — 세션 체크 이전에 실행
    const isValidCode = /^[a-zA-Z0-9\-_]{1,50}$/.test(productCode);
    if (!isValidCode) {
      return NextResponse.json({ error: '잘못된 상품 코드' }, { status: 400 });
    }

    // CSRF 검증 (상태 변경 요청 보호)
    const csrf = validateCsrfAndRespond(_req, 'Generate Detail Images');
    if (!csrf.valid) return csrf.response!;

    const session = await getSession();
    if (!session?.userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const userId = parseInt(session.userId, 10);
    const isAdmin = await isMallAdmin(userId);
    if (!isAdmin) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    // 1. 상품 + 콘텐츠 조회
    const product = await prisma.cruiseProduct.findUnique({
      where: { productCode },
      include: { MallProductContent: true },
    });
    if (!product) {
      return NextResponse.json({ error: '상품을 찾을 수 없습니다.' }, { status: 404 });
    }

    // 2. layout 파싱
    const rawLayout = product.MallProductContent?.layout;
    const layout: Record<string, unknown> = rawLayout
      ? (typeof rawLayout === 'string' ? JSON.parse(rawLayout) : rawLayout as Record<string, unknown>)
      : {};

    // 3. 데이터 조합 (DB 데이터 → DetailImageData)
    const data: DetailImageData = {
      productCode,
      packageName:   product.packageName,
      cruiseLine:    product.cruiseLine,
      shipName:      product.shipName,
      nights:        product.nights,
      days:          product.days,
      basePrice:     product.basePrice,
      maxPrice:      (product as Record<string, unknown>).maxPrice as number | null ?? null,
      thumbnail:     product.MallProductContent?.thumbnail ?? null,
      destination:   (layout.destination as string) || '',
      isPopular:     product.isPopular,
      isRecommended: product.isRecommended,
      isPremium:     (product as Record<string, unknown>).isPremium as boolean ?? false,
      hasEscort:     product.MallProductContent?.hasEscort || (layout.hasEscort as boolean) || false,
      hasLocalGuide: product.MallProductContent?.hasLocalGuide || (layout.hasLocalGuide as boolean) || false,
      hasCruisedotStaff: product.MallProductContent?.hasCruisedotStaff || (layout.hasCruisedotStaff as boolean) || false,
      hasTravelInsurance: product.MallProductContent?.hasTravelInsurance || (layout.hasTravelInsurance as boolean) || false,
      rating:        (layout.rating as number) ?? 4.5,
      reviewCount:   (layout.reviewCount as number) ?? 0,
      includedItems: (layout.included as string[]) || [],
      excludedItems: (layout.excluded as string[]) || [],
      itineraryDays: (layout.itinerary as DetailImageData['itineraryDays']) || [],
      pricingRows:   (layout.pricing as DetailImageData['pricingRows']) || [],
      bookingInfo:   (layout.bookingInfo as string[]) || [],
    };

    // 4. 이미지 생성
    const outputDir = path.join(process.cwd(), 'public', 'uploads', 'detail', productCode);
    logger.log(`[generate-detail-images] Starting for ${productCode}...`);
    const results = await generateDetailImages(data, outputDir);
    logger.log(`[generate-detail-images] Done: ${results.length} images`);

    // 5. layout.blocks 업데이트 (기존 데이터 보존)
    const newBlocks = results.map((r, i) => ({
      id: `gen_${i + 1}`,
      type: 'image',
      url: r.url,
      alt: r.section,
    }));

    const updatedLayout = {
      ...layout,
      blocks: newBlocks,
      autoGenerated: true,
      autoGeneratedAt: new Date().toISOString(),
    };

    // 6. DB 저장
    await prisma.mallProductContent.upsert({
      where:  { productCode },
      update: {
        layout:    updatedLayout,
        thumbnail: results[0].url,  // 타이틀 이미지를 썸네일로
      },
      create: {
        productCode,
        layout:    updatedLayout,
        thumbnail: results[0].url,
        isActive:  true,
      },
    });

    return NextResponse.json({
      success: true,
      images: results.map(r => ({ section: r.section, url: r.url })),
      message: `상세페이지 이미지 ${results.length}개가 생성되었습니다.`,
    });
  } catch (error: unknown) {
    logger.error('[generate-detail-images] Error:', error);
    return NextResponse.json({ error: '이미지 생성 중 오류가 발생했습니다.' }, { status: 500 });
  }
}
