'use client';

import { useState, useEffect } from 'react';
import { LandingCommentList } from './LandingCommentList';
import { LandingCommentForm } from './LandingCommentForm';

interface Comment {
  id: number;
  authorName: string;
  content: string;
  createdAt: string;
  isAutoGenerated?: boolean;
  isMine?: boolean; // 본인 댓글 여부
}

interface LandingCommentsSectionProps {
  slug: string;
  initialComments: Comment[];
  commentEnabled: boolean;
  isLandingPageOwner?: boolean; // 랜딩페이지 소유자 여부
  isBossUser?: boolean; // boss 사용자 여부
}

export function LandingCommentsSection({ slug, initialComments, commentEnabled, isLandingPageOwner: initialIsOwner, isBossUser: initialIsBoss }: LandingCommentsSectionProps) {
  const [comments, setComments] = useState<Comment[]>(initialComments);
  const [isLoading, setIsLoading] = useState(false);
  const [isLandingPageOwner, setIsLandingPageOwner] = useState(initialIsOwner || false);
  const [isBossUser, setIsBossUser] = useState(initialIsBoss || false);

  const loadComments = async () => {
    setIsLoading(true);
    try {
      const response = await fetch(`/api/public/landing-pages/${slug}/comments`);
      const data = await response.json();
      if (data.ok && data.comments) {
        setComments(data.comments);
        setIsLandingPageOwner(data.isLandingPageOwner || false);
        setIsBossUser(data.isBossUser || false);
      }
    } catch {
      // 댓글 로드 실패 시 빈 목록 유지
    } finally {
      setIsLoading(false);
    }
  };

  const handleCommentAdded = () => {
    loadComments();
  };

  const handleCommentUpdated = () => {
    loadComments();
  };

  if (!commentEnabled) {
    return null;
  }

  return (
    <section className="lp-card" aria-labelledby="lp-comment-title">
      <div className="lp-section-label">실제 후기</div>
      <h2 id="lp-comment-title" className="lp-section-title">
        댓글
      </h2>
      
      {/* 댓글 목록 */}
      <LandingCommentList 
        comments={comments} 
        slug={slug} 
        onCommentUpdated={handleCommentUpdated}
        isLandingPageOwner={isLandingPageOwner}
        isBossUser={isBossUser}
      />
      
      {/* 댓글 작성 폼 */}
      <LandingCommentForm 
        slug={slug} 
        onCommentAdded={handleCommentAdded}
      />
    </section>
  );
}


